disnake/ext/commands/converter.py
disnake/utils.py

Fix regex links so they point to discord.gg and not disnake.gg

Fix regex links

---

disnake/utils.py

Allow the user to parse their bot token to get the user id and other data from it.
Sadly there's not much use for this feature as the clientuser is created right on start during login.

Add a parse_token function

---

disnake/client.py
disnake/ext/commands/__init__.py
disnake/ext/commands/params.py
disnake/ext/commands/slash_core.py
disnake/interactions/application_command.py
examples/slash_commands/option_choice.py
examples/slash_commands/param.py

An implementation of `Param` - a fastapi-like way to describe options of a slash command using descriptor-like defaults. See dislash.py for a beta implementation.
(and also my tests)
```py
from pprint import pformat, pprint
from typing import Literal
import disnake
from disnake.ext import commands
bot = commands.Bot("test!", test_guilds=[570841314200125460])
Foo = commands.option_enum({"My Foo": "foo", "Your bar": "bar", "Their baz": "baz"})
@bot.slash_command(guild_ids=[570841314200125460])
async def command(
inter: disnake.ApplicationCommandInteraction,
required: str = commands.Param(description="first required"),
required_: int = commands.Param(..., desc="second required"),
member: disnake.Member = commands.Param(lambda inter: inter.author, desc="defaults to the author"),
channel: …
```

Implement Param

---

disnake/ext/commands/params.py
examples/slash_commands/param.py

Allow usage such as:
```py
def get_username(inter, user: disnake.User) -> str:
return user.name + '#' + user.discriminator # str(user) is better here but shhhh
async def advanced_converters(
inter: disnake.ApplicationCommandInteraction,
username: str = Param(name="user", desc="A user", conv=get_username)
):
...
```

Add support for annotated converters

---

disnake/ext/commands/errors.py
disnake/ext/commands/params.py

Does `ConversionError` really use to require a fucking Converter class? Man what the hell was danny thinking.

Properly raise ConversionError for Param

---

docs/_templates/layout.html

A small fix to the icons on the documentation's header. Mass changing "discord" to "disnake" caused the icon to break:
With this fix it should now look like this:
I have not actually tested this since its too much effort for such a small change, but feel free to test if need be 😃.

Fix discord icon on docs template

---

disnake/guild.py
disnake/http.py
disnake/types/audit_log.py
disnake/types/guild.py

While still in experiment, Discord is adding a feature to allow a server to display a progress bar for how many boosts are needed to get to the next level.
We shouldn't merge this quite yet, as it's not fully testable yet.

Add support for boost progress bar

---

disnake/abc.py
disnake/embeds.py
disnake/interactions/base.py
disnake/message.py
disnake/webhook/async_.py

Instead of forcing users to use embeds with `attachment://file.png` and attaching the files themselves, it should be abstracted behind a simple kwarg.
All of this stuff should seriously be handled in just a single function. Why do we have like 5 implementations of the same thing?

Add a file argument to embed.set_image

---

disnake/http.py
disnake/threads.py

Discord recently added support for fetching individual thread members,
which does not require the members intent.
Docs PR:
https://github.com/discord/discord-api-docs/pull/3998

Add support for fetching individual thread members

---

disnake/abc.py
disnake/interactions/base.py
disnake/message.py
disnake/webhook/async_.py
disnake/webhook/sync.py

- Updated descriptions of `file`/`files` and `embed`/`embeds` parameters to match in the entire project, also changing the order a bit to match the parameter specifications
- Added support for the `attachments` parameter in most places, which allows removing existing attachments on edit and was missing previously
- Added support for files to `inter.response.edit_message`, and removed the `attachments` parameter on it for now (see docstring for details)
Kind of but not really a breaking change, since the `attachments` parameter got removed; it wasn't working anyway.

Adjust docstrings, add support for `files` and `attachments` parameters to more methods

---

disnake/file.py
disnake/http.py
disnake/interactions/base.py
disnake/message.py
disnake/types/message.py
disnake/webhook/async_.py
disnake/webhook/sync.py

This implements attachment descriptions; they are already available, but gated behind an experiment in clients (`2021-09_inline_attachment_uploads`).
There is a change in the attachment handling, which would've generally resulted in previous attachments not being kept by default on edit anymore, *if* new files are also being uploaded.
This would affect types that don't contain information about existing attachments, i.e. all types except `Message` and `InteractionMessage`.
To fix this, the original message will be fetched for those types and existing attachments will carry over from that, if new files are being added and the developer didn't explicitly provide the `attachments` kwarg.
Providing existing *and* new attachments in the `attachments` list like this when new files are being …

Add attachment descriptions

---

disnake/flags.py
disnake/raw_models.py
disnake/state.py
disnake/types/raw_models.py
docs/api.rst

Followup to 659966ee528cf36d87b66c3cf9b4967e318063d0 and #107.
This PR adds an `on_raw_member_screening_reject` that'll always fire regardless of the `members` intent; the previously added `on_member_screening_decline` is also renamed to `on_member_screening_reject`.

Add 'on_raw_member_screening_reject' event, rename previous event

---

disnake/interactions/application_command.py
docs/api.rst
docs/whats_new.rst

I got the following warnings while building the documentation with sphinx.
```
C:\Users\...\Documents\disnake\disnake\interactions\application_command.py:docstring of disnake.interactions.application_command.ApplicationCommandInteraction:79: WARNING: duplicate object description of disnake.ApplicationCommandInteraction.type, other instance in api, use :noindex: for one of them
C:\Users\...\Documents\disnake\disnake\app_commands.py:docstring of disnake.app_commands.Option:1: WARNING: duplicate object description of disnake.Option, other instance in api, use :noindex: for one of them
C:\Users\...\Documents\disnake\disnake\app_commands.py:docstring of disnake.app_commands.Option:1: WARNING: duplicate object description of disnake.app_commands.Option, other instance in api, use :noindex: for …
```

Fix documentation warnings.

---

disnake/__init__.py
disnake/app_commands.py
disnake/custom_warnings.py
disnake/ext/commands/base_core.py
disnake/ext/commands/interaction_bot_base.py
disnake/utils.py
docs/api.rst

This PR replaces calls like `print('[WARNING] ...')` with `warnings.warn(...)`, and fixes displaying deprecation warnings.

Improve warnings, fix `DeprecationWarning` filters

---

disnake/ext/commands/params.py

Currently, we get parameters by simply indexing the first parameter if it's not within a cog and the second parameter if it is within a cog. This approach holds us back from doing some more complex things. Below is an example of that.
The example below shows an application where the config (settings) are needed within most commands. The decorator will inject a parameter, so there's easy access to the config. The config for each guild is cached, and the decorator would handle the logic for updating and retrieving this internal cache.
```py
def settings(fn):
async def decorator(cls, interaction, *args, **kwargs):
settings = interaction.bot.settings[interaction.guild.id]
await disnake.utils.maybe_coroutine(fn, cls, settings, interaction, *args, **kwargs)
return decorator
class …
```

Change how params are detected

---

disnake/ext/commands/interaction_bot_base.py
docs/ext/commands/api.rst

I also fixed some warnings I got, here is the full trace back:
```
C:\Users\...\Documents\disnake\disnake\ext\commands\interaction_bot_base.py:docstring of disnake.ext.commands.interaction_bot_base.InteractionBotBase.after_slash_command_invoke:1: WARNING: more than one target found for cross-reference 'after_invoke': disnake.ext.commands.Bot.after_invoke, disnake.ext.commands.InvokableSlashCommand.after_invoke, disnake.ext.commands.SubCommand.after_invoke, disnake.ext.commands.SubCommandGroup.after_invoke, disnake.ext.commands.InvokableUserCommand.after_invoke, disnake.ext.commands.InvokableMessageCommand.after_invoke, disnake.ext.commands.Command.after_invoke, disnake.ext.commands.Group.after_invoke
C:\Users\...\Documents\disnake\disnake\ext\commands\interaction_bot_base.py:docstring of …
```

Add `InteractionBot` and `AutoShardedInteractionBot` documentation.

---

disnake/ext/commands/slash_core.py

The expression `if not` is automatically expand the arguments of a slash command from the function signature.
However, say if a user wants to explicitly state that the slash command takes no arguments (even if the function it calls does), they can't. This is because `bool([]) == False`.
Instead it would be much more appropriate to use `is None` for the check in this situation.

Check if options is None instead of if it evals false

---

disnake/app_commands.py
disnake/ext/commands/base_core.py

Returns the old kwargs in such objects as:
- `GuildApplicationCommandPermissions`
- `PartialGuildApplicationCommandPermissions`
- `UnresolvedGuildApplicationCommandPermissions`
Fixes a reference in `commands.guild_permissions`

Rolled back breaking changes in XXXApplicationCommandPermissions objects

---

disnake/app_commands.py
disnake/utils.py

Better implementation of `from_dict` in
- `SlashCommand`
- `UserCommand`
- `MessageCommand`
- `Option`
- `OptionChoice`
Previous implementation wasn't solid enough to handle any sudden payload changes.

Fixed `from_dict` in app commands

---

disnake/ext/commands/interaction_bot_base.py

Improves the existing `get_slash_command` and makes it work like `get_command`

Made "get_slash_command" work like "get_command"

---

disnake/types/invite.py

Fixes a broken import of `_GuildPreviewUnique`, caused by https://github.com/DisnakeDev/disnake/commit/a90bc3852f91fcb8e3f1c1a0637f972a8d18c345#diff-63bdc218be73643008bcebbf87dc59c9667f5d73adfb957e69679b876dbebc86.
Not an issue at runtime as types are only imported when type checking, but still technically broken.

Fix broken import in invite types

---

disnake/channel.py
disnake/guild.py
disnake/http.py
disnake/message.py
disnake/threads.py

This PR adds support for the `slowmode_delay` parameter on `TextChannel.create_thread` and `Message.create_thread`.
It also adds the previously missing `invitable` parameter to `TextChannel.create_thread`, which was already supported in `HTTPClient.start_thread_without_message`.
~~The slowmode parameter on channel threads (not message threads) doesn't seem to be deployed yet, sending it currently does not enable slowmode. I'll keep this PR as a draft for now because of that, and check back in a while to make sure the change is actually deployed.~~
fixed.
ref:
https://github.com/discord/discord-api-docs/commit/d56be860c5dd4c04e80337556d82eb3a04f971a2
---
~~update re slowmode on channel threads:~~

Support setting slowmode on thread creation

---

docs/ext/commands/slash_commands.rst

Fixes the link found in the new section of the slash commands docs ([here](https://docs.disnake.dev/en/latest/ext/commands/slash_commands.html?highlight=injections#injections)).
EDIT: not sure why I mentioned "commit" when it's actually a file.

Fix injections link to commit in docs

---

README.ja.rst

- Replaced links and discord badge to point at disnake's discord
- Added slash commands and context menu examples (kept the wording in English and just added "example" in Japanese later)
- Added the disnake banner
The docs link to discord.py's Japanese docs was replaced as well, but the link points towards the default (English) disnake docs.
I've also replaced the `python3.6-dev` mention to `3.8` to reflect the new requirements (this should probably be done for the English README too).

Update JP readme to match the English one

---

.gitignore
disnake/abc.py
disnake/channel.py
disnake/ext/commands/context.py
disnake/interactions/application_command.py
disnake/interactions/base.py
disnake/message.py
disnake/state.py
disnake/webhook/async_.py

Text in Voice Channels is an upcoming feature in Discord that effectively grants Voice Channels a companion text channel. According to various Discord developers:
> This change should be pretty simple, since the regular text channel APIs all work the same on voice channels - the key change you'll have to accommodate is that text message content is now coming from voice channels (type GUILD_VOICE)
> we'd like to have this on stage channels at some point. but will be exclusively guild VCs for launch
Additional information:
- Text in Voice Channels can have webhooks
- Pins in Text in Voice Channels are not exposed in the UI, but the API exists (whether or not the API will be blocked in the future is TBD)
- Text in Voice Channels may be interaction sources
- Before release, trying to send …

Add support for Text in Voice Channels

---

disnake/permissions.py

This PR adds the `start_embedded_activities` (`1 << 39`) permission, added in https://github.com/discord/discord-api-docs/commit/839ef50c01069a00df53acf803d46c8d5adba034.

Add `start_embedded_activities` permission

---

disnake/ui/button.py
disnake/ui/item.py
disnake/ui/select.py
disnake/ui/view.py

This PR updates the `ui.button`/`ui.select` decorator annotations. While the existing code works fine and types are technically correct, `View.__init__` later replaces the callback with its associated item:
https://github.com/DisnakeDev/disnake/blob/f5c8c4a8d1cc51f8068c6ffc4e018b67cd96c70d/disnake/ui/view.py#L167-L170
This results in type checkers showing errors on code like `self.button.disabled = True` (where `self.button` is a method decorated with `ui.button`), as `self.button` is considered to be the same type as the decorated callback, while it is actually the associated item at runtime.

Fix button/select decorator return types

---

disnake/channel.py
disnake/raw_models.py
disnake/state.py
disnake/types/raw_models.py
docs/api.rst

This PR fixes typing events for DMs in cases where the bot didn't create the DM channel in the same session (and as such it wasn't cached). Previously, `DMChannel._from_message` would always set `recipient = None`, which resulted in typing events not being dispatched.
The recipient is now taken from the cache for both `MESSAGE_CREATE` and `TYPING_START` events, which should generally fix `channel.recipient`.
Fixes #175.

Fix dispatch of typing events in DMs

---

disnake/player.py
disnake/webhook/async_.py
disnake/webhook/sync.py

This PR replaces leftover calls to `json.loads` with `utils._from_json`, which uses orjson if available.
Supersedes #147.

Replace `json.loads` with `utils._from_json`

---

disnake/interactions/base.py

This PR adds updates the docstring of `Interaction.send`, hopefully clearing up confusion around the return value.
Appreciate any suggestions to further improve these docs.

Clarify `Interaction.send` docs

---

disnake/interactions/application_command.py
disnake/interactions/base.py

This PR fixes #108 and #180, and basically tries to get the object from the cache, and if it fails, it returns the partial object obtained from the API.
With this implementation, you will need to have: `members`, `guilds` and `presences` intents in order to get the member's status, as well as other things. (See #108)
And `guilds` intents to get the full channel. (See #180)

Try to get object from cache first.

---

disnake/channel.py
disnake/enums.py
disnake/http.py
disnake/message.py
disnake/threads.py
disnake/types/channel.py
disnake/types/threads.py
docs/api.rst

Building on @Victorsitou's solid base implementation, I present to you #186 v2.0, now with 50% more bells and whistles and other incredible features\*.
<sup>\* batteries not included</sup>
This PR adds a `ThreadArchiveDuration` enum with the (currently four) valid values, and renames the old `ThreadArchiveDuration` to `ThreadArchiveDurationLiteral` (there were no name conflicts, this is just to improve readability).
Resolves #181.
- *maybe? `disnake.types.ThreadArchiveDuration` is now `ThreadArchiveDurationLiteral`*

Add `ThreadArchiveDuration` enum

---

README.md
docs/version_guarantees.rst

This PR updates the version guarantees in the documentation to more accurately reflect the versioning scheme the library is currently following, and also adds a note about dependency pinning to the README.

Update version guarantees in docs

---

disnake/interactions/base.py
disnake/message.py
disnake/webhook/async_.py
disnake/webhook/sync.py

This PR ensures that any files used in requests will be closed once the request finishes, instead of keeping them open until they are garbage collected.
Not closing files is technically not an issue in most cases, as CPython already closes files when they're garbage collected, usually once the ref count drops to zero. However, this behavior might be different in alternative implementations, and it's also just good practice in general.

Always close files after requests

---

disnake/ext/commands/interaction_bot_base.py
docs/ext/commands/additional_info.rst
docs/ext/commands/index.rst

Fixed a small sync algo bug that caused the "This is a deprecated local command which is now deleted" message if you invoke an application command before the sync finishes.

Fixed a small command synchronization bug

---

disnake/message.py

This is basically to follow the same default value in all functions that use it.

`fail_if_not_exists` in `Message.reply()` is now True by default.

---

disnake/ext/commands/params.py
tests/cogs/slash_commands.py

`GuildCommandInteraction` failed to mark the command as guild-only

Fixed GuildCommandInteraction

---

disnake/flags.py
disnake/raw_models.py
disnake/state.py
disnake/types/raw_models.py
docs/api.rst

[as title]
The API is still actively changing (especially over the last few weeks) and this event isn't documented at all, so it's being removed again for now. Originally it seemed to work fine, however it looks like the event is now emitted even when completing screening, with no way to differentiate between someone leaving the server and completing membership screening.
Reverts #109 and 659966ee528cf36d87b66c3cf9b4967e318063d0.

Remove `on_member_screening_reject` event

---

disnake/guild.py
disnake/member.py

This PR adds support for `duration` (`float`/`timedelta`) and `until` (`datetime`) parameters to `Member.timeout` and `Guild.timeout`, as well as supporting `timedelta` parameters in `Member.edit(timeout=...)`.

Improve timeout method parameters

---

disnake/audit_logs.py

This PR adds the previously missing `AuditLogEntry.target` converter for guild scheduled events, which was already documented but not implemented yet.

Add audit log target converter for scheduled events

---

disnake/app_commands.py

Fixed an issue where the Korean slash_command name is supported in Discord but not in this module.

Add use Korean to slash_command()

---

disnake/interactions/application_command.py
disnake/interactions/base.py
disnake/interactions/message.py
disnake/types/interactions.py

The API is already providing those values.
ref:
https://github.com/discord/discord-api-docs/pull/4265

Add `locale` and `guild_locale` properties to interactions.

---

disnake/ext/commands/params.py

Fix for python3.10 union type aliasing syntax (`type | type`) for `Param`.

python 3.10 union type alias fix

---

disnake/abc.py
disnake/interactions/base.py
disnake/message.py
disnake/ui/__init__.py
disnake/ui/action_row.py
disnake/ui/button.py
disnake/ui/item.py
disnake/ui/select.py
disnake/ui/view.py
disnake/webhook/async_.py
docs/api.rst
docs/conf.py

This PR adds 2 things:
1) `ui.ActionRow` object for grouping components
2) `components` kwarg in all send methods

Added lower level components syntax

---

docs/_static/style.css
docs/conf.py
docs/extensions/builder.py

The `drop_down_icon.svg` file wasn't being copied by Sphinx since it wasn't referenced in any rst files. This PR adds a new option for specifying a list of images that should always be copied to the build directory.
<sup>Disclaimer: I have no idea if this is a good implementation (spoiler: it probably isn't), but it works™</sup>

Fix missing dropdown icon in docs

---

disnake/flags.py

I failed to test this flag, so if anyone could test this, I appreciate it. Also, I didn't want to make the flag name long, `failed_to_mention_roles_in_thread` might be good to avoid confusions, but it's too long :/
ref:
https://github.com/discord/discord-api-docs/pull/4282

feat(MessageFlags): Add `failed_to_mention_roles_in_thread` flag (1 << 8).

---

disnake/client.py
disnake/ext/commands/bot.py
disnake/ext/commands/interaction_bot_base.py
docs/ext/commands/slash_commands.rst

Fixes #157.
The output is pretty much unchanged:
<details>
<summary>Example log output</summary>
```py
2021-12-25 20:10:35,670: [INFO] (MainThread) disnake.ext.commands.interaction_bot_base: Application command synchronization:
GLOBAL COMMANDS
===============
| NOTE: global commands can take up to 1 hour to show up after registration.
|
| Update is required: False
| To upsert:
|     -
| To edit:
|     -
| To delete:
|     -
| Type migration:
|     -
| No changes:
|     -
2021-12-25 20:10:35,672: [INFO] (MainThread) disnake.ext.commands.interaction_bot_base: Application command synchronization:
COMMANDS IN 521292111455453194
===============================
| Update is required: True
| To upsert:
|     <SlashCommand name='shutdown'>
| To edit:
|     -
| To delete:
|     -
| Type migration: …
```

Use logger for application command sync debug

---

disnake/ext/commands/interaction_bot_base.py

Added `InteractionBotBase.application_commands_iterator` property that uses `itertools.chain` to concatenate 3 iterators.
Some methods are now iterating through `.application_commands_iterator` instead of `application_commands` (a set) which is of course more efficient.

Minor refactoring of the sync algo

---

docs/_static/style.css
docs/conf.py
setup.py

This PR adds `sphinx-hoverxref`, which shows a preview tooltip of a linked page when hovering over the link. It unfortunately only works on readthedocs, since it uses rtd's API and using their API locally is a bit wacky due to CORS.
The API is unfortunately not incredibly fast (this is also noted in the [API docs](https://docs.readthedocs.io/en/stable/development/design/embed-api.html#current-implementation)), the first few requests sometimes take ~600-700ms; for some reason it seems to get faster after a few requests, not sure what's up with that. Still, I feel like this could be a useful feature, even if the loading times aren't incredible they're still reasonably fast.
`sphinxcontrib-websupport` was removed as it was only used as a workaround in a time where readthedocs was having …

Show tooltips when hovering over links in docs

---

docs/conf.py

see title
Fixes CORS issues which sometimes occurred (or rather, sometimes *didn't* occur even though they should've) due to a race condition with `beforeSend` on readthedocs.
also see https://github.com/readthedocs/sphinx-hoverxref/issues/165

Use proxied readthedocs API for hoverxref

---

disnake/http.py

Bump to http api version 9
the only change from v8 to v9 were adding thread channels to gateway events
and there's no http api differences between v8 to v9

use http version 9

---

disnake/app_commands.py
disnake/errors.py
disnake/http.py
disnake/integrations.py
disnake/types/interactions.py
disnake/utils.py

This PR updates the typings for application commands, and makes `app_commands.py` fully typed (no more `Dict[str, Any]` or `Any` \o/ ).
Changes in no particular order:
- `ApplicationCommand` and subtypes are now slotted
- `ApplicationCommand.__init__` and its subtypes no longer take `**kwargs`, common parameters in application command payloads are now handled by `_update_common` which is called by `from_dict`. I tried a few different solutions and this was the one that worked best, since calling `__init__` from a `classmethod` is tricky with inheritance
The `**kwargs` were never meant to be set by the user and were only populated from API response payloads, so this change should be fine.
- `_get_and_cast` is `_maybe_cast` now and works a bit differently, while it unfortunately doesn't …

Improve `app_commands.py` typing

---

disnake/ext/commands/params.py
examples/slash_commands/autocomplete.py
examples/slash_commands/converters.py
examples/slash_commands/injections.py
examples/slash_commands/param.py
test_bot/cogs/injections.py
test_bot/cogs/slash_commands.py

Use `x: Range[1, 2]` instead of `x: int = Param(ge=1, le=2)` in slash commands
```py
async def ranges(
inter: disnake.CommandInteraction,
ranking: commands.Range[1, 10],
negative: commands.Range[..., 0],
fraction: commands.Range[0, 1.0],
):
"""Command with limited ranges
Parameters
----------
ranking: An integer between 1 and 10
negative: An integer lower than 0
fraction: A floating point number between 0 and 1
"""
```
```py
Ranking: Type[int] = commands.Range[1, 10]
Negative: Type[int] = commands.Range.create(lt=0)
Fraction: Type[float] = commands.Range.create(min_value=0, max_value=1.0)
async def seprate_ranges(
inter: disnake.CommandInteraction,
ranking: Ranking,
negative: Negative,
fraction: Fraction,
):
...
```

Implement Range in slash commands

---

disnake/ext/commands/params.py
docs/ext/commands/api.rst
examples/slash_commands/param.py
test_bot/cogs/slash_commands.py

Use  `x: LargeInt` instead of `x: int = Param(large=True)`

Implement `LargeInt` in slash commands.

---

disnake/ext/commands/interaction_bot_base.py

It was impossible to register commands of different types with the same name. The reason was one of the internal functions that compares old and new commands. It mapped them like `{name: cmd}` instead of `{(name, type): cmd}`

Fixed a rare command sync bug

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
pyproject.toml
requirements_dev.txt

- feat: use taskipy for development
- chore: update references to pre-commit to use the linting tasks
Adds taskipy for development. Means we don't have to remember long commands, or type them over and over.
If you have other commands that have to be typed over and over, please share them!

add taskipy for local dev

---

disnake/interactions/base.py

added show_message to defer, which for component interactions sends a type 5 response instead of 6.

fix: allow deferring messages on component interactions

---

disnake/guild.py
disnake/http.py
disnake/sticker.py
disnake/types/template.py
disnake/widget.py

Went through all the endpoints which support reason and added the missing ones (well, only one heh).
1. Add support for reason in `edit_widget` (`PATCH /guilds/{guild_id}/widget`) and updated `Guild.edit_widget`.
2. Added `Widget.edit`, probably unnecessary.
3. Changed `CreateTemplate` type as the old one was pointing to a different [endpoint](https://discord.com/developers/docs/resources/guild-template#create-guild-from-guild-template).
4. Add support for reason in `create_party`, which is unused by the library.
5. `reason` is now a kwarg in create/edit/delete sticker endpoints.
- _Kind of, since `CreateTemplate` type was changed, but I doubt it's used._
- `reason` is now a kwarg in create/edit/delete sticker endpoints.

Add missing support for reason in `http.py`.

---

disnake/ext/mypy_plugin.py
disnake/mypy_plugin.py
docs/ext/commands/slash_commands.rst

This PR adds documentation for `ext.commands.Range`, as well as a mypy plugin which fixes `Range` annotations.
Apparently mypy doesn't understand/handle custom `__getitem__` in metaclasses or `__class_getitem__` outside of generics, which resulted in several type-checking issues (e.g. `"Range" expects no type arguments, but 2 given`). The plugin helps mypy infer the resulting type correctly.

Add mypy plugin for `commands.Range` annotations

---

disnake/app_commands.py

This PR improves the error message for invalid command names, and adds validation for option names.

Improve validation of slash command/option names

---

disnake/ui/view.py

<sup>First bug</sup>
This PR fixes a bug for when a view is refreshed, and it has a link button, since they aren't dispatchable, they won't be in this dict,
so it tries to get the link button from it,
https://github.com/DisnakeDev/disnake/blob/2e5488572cc25432101da3328f44ae638d05dae6/disnake/ui/view.py#L409-L413
and since it isn't there, it'll raise a `KeyError` error, and then it tries to create a new item (`_component_to_item`)
https://github.com/DisnakeDev/disnake/blob/2e5488572cc25432101da3328f44ae638d05dae6/disnake/ui/view.py#L77-L81
which calls `Button.from_component` which defines `row` to `None`
https://github.com/DisnakeDev/disnake/blob/2e5488572cc25432101da3328f44ae638d05dae6/disnake/ui/button.py#L203-L213
There is also another related bug, but I really don't understand why it …

fix: bugs with link buttons

---

disnake/ext/commands/converter.py

fixes bug introduced with 1a4e73d59932cdbe7bf2c281f25e32529fc7ae1f
which required messages be in the cache if no channel id was provided, contrary to the docstring

fix: message converter now reattempts to fetch messages

---

disnake/invite.py

closes #296
implements on PartialInviteGuild objects:
- nsfw_level
- vanity_url_code

feat: add missing attributes to invite guild objects

---

disnake/guild_scheduled_event.py
disnake/interactions/application_command.py
disnake/member.py
disnake/types/member.py
disnake/user.py

This PR adds a new kwarg to `Member.__init__` which allows passing user data in separately, instead of modifying the member data at the call site. The functionality of `.types.member` is mostly unchanged, the types were just renamed a bit to make more sense.

Improve member deserialization with separate user data

---

disnake/app_commands.py
disnake/client.py
disnake/ext/commands/interaction_bot_base.py
disnake/guild.py
disnake/state.py
docs/api.rst

This PR introduces new `API*Command` types, subtypes of the respective `*Command` types but with the additional fields returned by the API, most importantly the `id`. These fields were previously present in `ApplicationCommand` but marked optional since no distinction was made between command objects sent to the API and those returned by it.
The core benefit of this is that the `id` in objects returned by `application_command_factory` is no longer optional.
<sup>fun fact: this fixes exactly one (1) pyright error! just 95 more to go, woo</sup>

Add separate types for command objects returned by the API

---

disnake/threads.py
disnake/types/threads.py

Discord doesn't provide this field anymore. It will be deleted in a future version (probably version 2.5).
ref:
https://github.com/discord/discord-api-docs/pull/3108

docs(Thread): add deprecation warning to `archiver_id`

---

disnake/asset.py
disnake/guild.py
disnake/guild_scheduled_event.py
disnake/http.py
disnake/types/guild_scheduled_event.py
disnake/webhook/async_.py
test_bot/cogs/guild_scheduled_events.py
test_bot/main.py

Discord pushed it into canary last night, the cdn endpoint is the one that the client uses.
note: there isn't any PR in discord-api-docs, but the `image` field has been there for a while.
Todo:
ref:
https://github.com/Discord-Datamining/Discord-Datamining/commit/d633cd1d95e097d9c97beaef42926d958395bc7c
https://github.com/discord/discord-api-docs/pull/4380

feat(GuildScheduledEvent): add support for image

---

disnake/channel.py
disnake/ext/commands/params.py

support disnake.Thread annotations in slash command params
```py
@bot.slash_command(name="threads")
async def threads(inter: disnake.CommandInteraction, thread: disnake.Thread):
"""Threads"""
await inter.response.send_message("ok.", ephemeral=True)
```

feat: support disnake.Thread annotations in slash command params

---

disnake/ext/commands/interaction_bot_base.py
disnake/interactions/application_command.py
disnake/interactions/base.py
disnake/interactions/message.py
disnake/message.py
disnake/state.py
disnake/types/interactions.py
disnake/types/message.py
docs/api.rst

This PR is a small refactor of interaction types, primarily removing some `# type: ignore`s and improving the types of a few properties.
Changes:
- Rename `types.MessageInteraction` (a property on messages, represents the interaction that caused it) to `types.InteractionMessageReference`
- Split `types.Interaction` into `BaseInteraction`, `Interaction`, `ApplicationCommandInteraction`, and `MessageInteraction`; some properties were changed according to the docs (mostly changing some optional -> non-optional)
- Update interaction parsing according to `types.*Interaction` changes, which allowed removing some `# type: ignore`s. This should hopefully not result in any exceptions (the docs specify `channel_id` as optional, I can't imagine a situation where it would be though, outside of `PING` …

Minor refactor of interaction types

---

disnake/abc.py
disnake/channel.py
disnake/threads.py

Add ignore_timeout parameter to permission_for methods.
This allows a developer to more easily view the permissions of a user without needing to 
check this themselves.
Leads way to support this in `commands.has_permissions`

feat: support timeouts in permissions_for

---

disnake/ext/commands/converter.py

This PR adds missing annotations in `converter.py`, and changes `Converter.convert` to use `Union[Context, ApplicationCommandInteraction]` instead of `Context`. No functional changes, except for `_get_from_guilds`.

Improve `converter.py` annotations

---

disnake/gateway.py
disnake/http.py
disnake/types/gateway.py
disnake/voice_client.py

This PR adds annotations to `gateway.py` and adds `TypedDict`s for all the currently used gateway payloads.
The functionality is mostly the same, with only a few minor adjustments:
- Updated `IDENTIFY` payload
- remove `$referrer`, `$referring_domain`, `v` fields (obsolete)
- always add `intents`, required by API and not optional in code anyway
- use `activities` instead of `game` (obsolete)
- Updated presence data (in identify and presence update)
- always include non-null value for status by defaulting to `"online"` (the API seems to be perfectly fine with a null value, but the docs say otherwise, so we're going with that)
- `since` is an int, not a float
- Added missing `ssrc` to voice `SPEAKING` payload (also works fine without it, but again, not explicitly stated as optional in the …

Add annotations to `gateway.py`

---

disnake/ext/commands/cooldowns.py

Dynamic cooldowns now work with default bucket types as well.

Fixed dynamic cooldown (BucketType.default case)

---

disnake/guild.py

as title, fixes a missing `return` and updates the docstring (partially taken from #275)

fix(Guild): missing return in `get_command`

---

examples/views/disable_view.py

`on_timeout` gets triggered even after the view is removed via the `remove` button, which causes a disabled `disable` button to appear.
**Expected behavior:** View is stopped after either of the buttons are pressed
**Actual behavior:** View times out if the `remove` button is pressed.
**Solution:** Call `self.stop()` in the `remove` button.

Fix undesired behavior

---

disnake/app_commands.py
disnake/ext/commands/params.py

Discord did an API change, making options in slash commands with no description broken, since Discord doesn't allow `\u200b`.
I'm not sure if Discord is going to fix this, but either way, using `-` is better

fix: slash commands options with no description

---

disnake/abc.py
disnake/channel.py
disnake/guild.py
disnake/interactions/base.py
disnake/permissions.py

- added Permissions.private_channel() classmethod
- Interaction.permissions returns an instance of the above in a private channel
- switched the view_channel and read_messages aliases
closes #312
closes #313

touch up permissions

---

disnake/guild.py

This was previously an undocumented feature of Danny’s Discord.py that I frequently use when chunking a guild without cache saving. Unfortunately it appears to have been removed in Disnake, despite its excellent use cases. 
I have added both documentation & re-added the functionality.
Example use case: members = await guild.chunk(cache=False)

Making guild.chunk() return a list of guild members.

---

disnake/__init__.py
disnake/ext/commands/params.py
docs/whats_new.rst

Backport of #338 for 2.3, bumps version to 2.3.2 and adds changelog for new 2.2.x and 2.3.x versions (the former is already in the [v2.2.x branch](https://github.com/DisnakeDev/disnake/tree/v2.2.x), but included again here for rtd).

Backport #338 to 2.3

---

disnake/ext/commands/slash_core.py

This PR fixes command caching and `InvokableSlashCommand.qualified_name` for names with uppercase chars, as the inner object (`body`/`option`) converts the name to lowercase, but command caching uses the (unmodified) `InvokableApplicationCommand.name` instead of `.body.name`.
Also adds `SubCommandGroup.body` which was missing before, to match the other types.
fixes #336

fix(slashcmd): improve handling of uppercase slash command names

---

disnake/abc.py

They're only used to create a `PermissionOverwrite`, [which accepts `Optional[bool]`](https://github.com/DisnakeDev/disnake/blob/5d1f3b2fb8d674f4cb55022031abbb7b4b6c6da6/disnake/permissions.py#L852).

`GuildChannel.set_permissions` kwargs can be `None`

---

disnake/abc.py
disnake/channel.py
disnake/threads.py

feat: jump to channel properties
these were not added to GroupChannel since
1) the integration has been discontinued and
2) those GroupChannels don't show up in the official user interface so jump urls aren't useful
added jump_url to all guild channels because of the tentative text in voice feature
and I don't see it being a problem to implement it this way
it was also the easiest way to implement it.
Closes #315

feat: jump to channel properties

---

disnake/abc.py
disnake/interactions/base.py
disnake/message.py
disnake/ui/action_row.py
disnake/webhook/async_.py

This PR makes the documentation for the `view` and `components` kwarg more consistent with the rest of the docs (regarding spelling and order), updates the error message in `components_to_rows` to match the definition of the `Components` union, and fixes an `isinstance` check to use `Sequence` instead of `list`.

fix: improve components parameter docs and `isinstance` check

---

disnake/guild.py
disnake/integrations.py
disnake/utils.py

Deprecates integration create, edit, sync and delete, see https://github.com/discord/discord-api-docs/pull/2087.
Integration deletion still works, but only on the bot's own integration, which ends up just being a `Guild.leave` with extra steps.
Also fixes the incorrect `stacklevel` in `utils.deprecated`.

deprecate: integration create, edit, sync and delete

---

disnake/enums.py
disnake/guild.py
disnake/http.py
disnake/widget.py
docs/api.rst

This PR adds functionality for fetching a guild's widget settings, as well as constructing a widget image's URL with one of the predefined styles.

feat: add widget settings, widget images

---

disnake/http.py

Hi,
I observed that the URL generated by `Guild.widget_image_url()` method was missing `/api/` parent endpoint, it generates:
```py
https://discord.com/guilds/{guild_id}/widget.png?style={style}
```
However, as per Discord API docs examples on [widget image](https://discord.com/developers/docs/resources/guild#membership-screening-object-widget-style-options) example, URL should be:
```py
https://discord.com/api/guilds/{guild_id}/widget.png?style={style}
```
which properly renders as correct widget image.
This PR hopefully fixes this issue. 😅

fix Guild.widget_image_url

---

disnake/http.py
disnake/member.py
disnake/types/member.py

https://discord.com/developers/docs/resources/channel#join-thread
> `PUT` `/channels/{channel.id}/thread-members/@me`
Additionally, removes an unused method from http.py, http.logout, while we're here. This endpoint can not be used by bots.

chore: use the proper http method for joining threads and remove unused methods

---

disnake/channel.py

Helps update to api v10, as type became required to provide.
Additionally adds some missing documentation around creating threads.

breaking: require one of message or type for creating a thread

---

disnake/message.py
disnake/threads.py

Adds support for specifying a reason with `Message.create_thread` or `Thread.delete`; note that in the latter case, the reason doesn't show up in the UI, but is still accessible through the API.

feat: support reason for `Message.create_thread` and `Thread.delete`

---

disnake/ext/commands/errors.py
disnake/ext/commands/params.py

adds `LargeIntConversionFailure` (named after PartialEmojiConversionFailure)
raising this custom error instead of a commands.errors.ConversionError
falls in line with the documentation for ConversionError, and allows the
end user to more easily handle exceptions for LargeInts that may 
not be easily convertable
additionally, added a missing except clause that lets exceptions propagate 
cleanly as documented
Debatable, but will continue to raise a exception dervived of CommandError. Just falls in line with the documentation now.

fix: add commands.errors.LargeIntConversionFailure

---

disnake/interactions/modal.py
disnake/types/interactions.py

This PR adds the `message` field to `ModalInteraction`, which exists if the modal was sent in response to a component interaction. This is currently undocumented, but was confirmed as intended here: https://discord.com/channels/613425648685547541/940752915109400617/944311209556074516

feat: add `message` field to `ModalInteraction`

---

disnake/errors.py
disnake/interactions/base.py

This PR adds the ability to use `InteractionResponse.edit_message` with `ModalInteraction`s whose associated modal was sent from a component interaction.
A new `InteractionNotEditable` exception is also being added, which is raised when trying to call `.edit_message` on an unsupported interaction type (application command, or modal without component interaction).
Depends on #363 and currently includes those changes (as such, disregard the changes in `modal.py` and `types/interactions.py`).

feat: support edit responses for modal interactions

---

disnake/permissions.py

Hi,
I saw that `create_private_threads` was put 2 times in `Permissions.private_channel` perm.
I believe one of them should be `create_public_threads` to be consistent with the perm's docstring. Hopefully this PR fixes that. 😅

fix Permissions.private_channel

---

disnake/appinfo.py
disnake/integrations.py

deprecates Application.summary, IntegrationApplication.summary, AppInfo.summary as the summary parameter is now deprecated and replaced with the description parameter.

chore: deprecate summary on application objects

---

disnake/interactions/__init__.py
disnake/webhook/__init__.py

sets `__all__` in `disnake.interactions.__init__` to prevent shadowing other modules
with the modules from the `disnake.interactions` namespace.

fix: no longer shadow disnake.message with disnake.interactions.message

---

docs/_static/custom.js
docs/_static/sidebar.js
docs/_static/style.css
docs/_templates/layout.html

Clean up issues that resulted from the doc's style update and were found in the following weeks:

Docs: post cleanup bugfixes

---

.github/workflows/lint.yml
pyproject.toml

- Fixes the `docs` task (broken by #311, oops)
- Updates the `actions/checkout` action to v3, notably also including the v2 changes (duh) which might speed things up a tiny bit as it won't fetch the entire repository by default any longer
- Makes all jobs use the same pip cache

build: update ci, fix tasks

---

disnake/invite.py
disnake/types/channel.py

Due to some discord api inconsistencies (and a minor doc update, https://github.com/discord/discord-api-docs/pull/4571), this is a simple implementation to fix `__str__`.
A future implementation of PartialInviteChannel will properly use the recipients key to 
provide a close equivalent of how the discord client shows a group DM name.
Unfortunately, the api currently is unclear as what information is provided in the 
recipients key for group dms. The documentation states the array is full user objects,
which is not the case from testing. As such, this has not been implemented.
This can be tracked at discord/discord-api-docs#4572
- fix: mark channel name as both optional and nullable in payload typings
- fix: make PartialInviteChannel.__str__ always return a string
closes #382

fix PartialInviteChannel.__str__

---

disnake/ext/commands/converter.py

Fixes an import issue in the `clean_content` converter. Also improves typing a tiny bit and makes more use of the `_utils_get` shorthand.
resolves #392

fix(converter): move import for `commands.clean_content`

---

examples/basic_bot.py

`_var` is meant to show that a name is *private*.
`var_` should be used if `var` name is already taken.
Reference: [PEP8](https://pep8.org/#descriptive-naming-styles)

Improve semantics

---

disnake/enums.py
docs/api.rst

```youtube = 755600276941176913``` this id is no longer valid
to run watch youtube together you must pass this id ```watch_together = 880218394199220334```

delete youtube = 755600276941176913

---

disnake/channel.py
disnake/guild.py
disnake/guild_scheduled_event.py
disnake/role.py
disnake/state.py
disnake/types/channel.py
disnake/types/guild_scheduled_event.py
disnake/types/voice.py

This PR updates a few field types and parameters of roles, scheduled events, and voice states, according to this api-docs commit: https://github.com/discord/discord-api-docs/commit/074e9305b45f3102266e79513c9f84ddb5697a05

fix: update types according to latest api-docs changes

---

disnake/enums.py
docs/api.rst

The `awkword` and `sketchy_artist` activities appear to be removed/disabled as well, similar to `youtube` in #408.

fix: remove awkword and sketchy_artist activities

---

docs/_static/scorer.js
docs/_static/searchtools.js

- removes duplicate search results by essentially backporting this https://github.com/sphinx-doc/sphinx/commit/262240dd251ea1a824b43c9502deb8d12d124aee to Sphinx 4.x
- fixes custom scorer which was inadvertently broken in https://github.com/Rapptz/discord.py/commit/70c73084b38c8788e6fda907c031f6eec2d13847
Note that fixing duplicate search results required copying Sphinx' builtin `searchtools.js` and modifying it, as there doesn't seem to be a proper way of hooking into the search result generation other than the scoring function, which can't be used to modify the results; the diff with the actually interesting changes is this one: https://github.com/DisnakeDev/disnake/compare/c602884400fd9d5e00c40a50960158b7c8ced853...shiftinv:docs/fix-search
comparison:
- original: …

docs: fix duplicate search results and custom scorer

---

disnake/ext/commands/cog.py
disnake/ext/commands/core.py
disnake/ext/tasks/__init__.py
disnake/member.py
disnake/ui/button.py
disnake/ui/select.py
docs/extensions/attributetable.py

Replaced all occurrences of `inspect.iscoroutinefunction` with the slightly more truthy `asyncio.iscoroutinefunction`.

chore: replaced `inspect.iscoroutinefunction` with `asyncio.iscoroutinefunction`

---

disnake/channel.py
disnake/client.py
disnake/guild.py
docs/api.rst
docs/ext/commands/api.rst

- remove default values for `message` and `type` in `TextChannel.create_thread` overloads
- fix broken documentation references to `Intents.message_content` and voice regions
- add documentation for new `LargeIntConversionFailure` exception

fix: minor typing and documentation improvements

---

disnake/flags.py
disnake/stage_instance.py
disnake/types/channel.py

This PR adds `StageInstance.guild_scheduled_event_id`, as well as a `.guild_scheduled_event` property which works as long as the proper intents are enabled.
ref: https://github.com/discord/discord-api-docs/pull/4583

feat: implement `StageInstance.guild_scheduled_event[_id]`

---

docs/_static/custom.js
docs/_templates/layout.html

Adds a few common keyboard shortcuts for focusing the search bar in the documentation:
- `ctrl+k`: algolia/docsearch (hence also used by sites like [discord.dev](https://discord.dev) and [guide.disnake.dev](https://guide.disnake.dev))
- `/`: commonly seen in a few applications; Sphinx 4.5 will [support](https://github.com/sphinx-doc/sphinx/commit/799385f5558a888d1a143bf703d06b66d6717fe4) it, GitLab uses it, algolia/docsearch also appears to support it
- `s`: GitHub + GitLab
preview: https://disnake--434.org.readthedocs.build/en/434/

feat: add documentation search hotkeys

---

disnake/ext/commands/cog.py

(Renamed my branch to have a less dumb dependency for ext-components but apparently that closed my pr, oops. Anyways, this is just a repost on a different branch name.)
Currently, listeners are added to a dict by event name, then stored in a list of functions for that event. This dict can be found in `CommonBotBase.extra_events`. This is achieved as follows:
```py
for name, method_name in self.__cog_listeners__:
bot.add_listener(getattr(self, method_name), name)
def add_listener(self, func: CoroFunc, name: str = MISSING) -> None:
name = func.__name__ if name is MISSING else name
...
if name in self.extra_events:
self.extra_events[name].append(func)
else:
self.extra_events[name] = [func]
```
However, when they're unloaded, they suddenly ignore the name:
```py
for _, method_name in …
```

fix(listeners): improve listener unloading behaviour

---

disnake/ext/commands/context.py
disnake/ext/commands/converter.py
disnake/ext/commands/core.py
disnake/ext/commands/params.py

This PR fixes #384, correcting an import cycle as well as adding support for Union[] inside the self and cog extractor function `isolate_self`.

fix: correct NameError by moving import out of type checking clause 

---

disnake/__init__.py
disnake/bans.py
disnake/guild.py
disnake/http.py
disnake/iterators.py

Discord changed the [Get Guild Bans](https://discord.com/developers/docs/resources/guild#get-guild-bans) API endpoint to support pagination.
This implements that change by making `Guild.bans` return an `AsyncIterator` supporting limit, before, and after.
`BanEntry` was moved from `disnake.guild` to `disnake.bans` to avoid circular imports.
`Guild.bans` is no longer a coroutine and returns an `AsyncIterator` of bans instead of a list.
```py
bans = await guild.bans()
bans = await guild.bans(limit=None).flatten()
```
More examples:
https://paste.nextcord.dev/?id=1648774261939651

feat!: update bans to use AsyncIterator pagination

---

disnake/state.py
docs/api.rst

Changes the `THREAD_CREATE` handling to dispatch a `thread_create` instead of `thread_join` event according to the `newly_created` field in the payload.
closes #323
ref: https://github.com/discord/discord-api-docs/commit/1875d80011ea62bf555ce807459ccf97950291e9
Previous attempt was #331, which partially changed how thread caching works. While this is certainly something that should be fixed, it should really be done separately.

feat(thread)!: support `newly_created`, add `on_thread_create` event

---

disnake/abc.py
disnake/http.py
disnake/interactions/base.py
disnake/message.py
disnake/webhook/async_.py
disnake/webhook/sync.py

The `content` parameter of `Message.edit` was unintentionally changed to be kwarg-only in a refactor a while ago, and while it has always been kwarg-only in the overloads (and any good IDE/linter/typechecker would've complained), some users seem to have relied on that.
This PR changes most `content` parameters of edit methods to support both positional and kwarg calls, and updates all types to `Optional[str]`. The serializing methods have always been calling `str()` anyway, but it's better to be explicit here, which helps avoid mistakes such as `.send(embed)` as well.
It also adds a default for the `files` parameter of `HTTPClient.edit_message`, which was changed some time ago as well.

fix: allow most `content` parameters to be positional, change types to `Optional[str]`

---

disnake/threads.py

the reason doesn't show up in the audit log for all parameter combinations,
but its worth adding as it *is* supported

chore: add missing reason parameter to Thread.edit

---

disnake/channel.py
disnake/http.py

https://github.com/discord/discord-api-docs/commit/68d862bb59c1482e49012f174cbce4a9bcc666e2?w=1
nb: without the `mention_everyone` permission, setting `notify_everyone=True` does nothing and currently doesn't result in a 403.

feat: add stage instance start notification

---

disnake/client.py
disnake/http.py
disnake/shard.py
docs/api.rst

Pretty self-explanatory; adds session start limit data to the client object, which was previously just dropped.
The contained `max_concurrency` value isn't being used, but given how the shard launching process currently works it's not really necessary.
resolves #390
- `HTTPClient.get_bot_gateway` return type changed

feat: add session start limit data

---

disnake/asset.py

* Adds `to_file` to all objects that use `AssetMixin` (`Asset`, `Emoji`, `PartialEmoji`, `Sticker`)
```py
@bot.command()
async def avatar_file(ctx: commands.Context[commands.Bot]):
file = await ctx.author.display_avatar.to_file()
await ctx.send(file=file)
@bot.command()
async def emoji_file(ctx: commands.Context[commands.Bot], emoji: disnake.Emoji):
file = await emoji.to_file()
await ctx.send(file=file)
@bot.command()
async def partial_emoji_file(ctx: commands.Context[commands.Bot], partial_emoji: disnake.PartialEmoji):
file = await partial_emoji.to_file()
await ctx.send(file=file)
@bot.command()
async def sticker_file(ctx: commands.Context[commands.Bot], message_id: int):
msg = await ctx.channel.fetch_message(message_id)
file = await msg.stickers[0].to_file()
await ctx.send(file=file) …
```

feat: to_file for Assets, Emojis, Stickers

---

disnake/activity.py
disnake/asset.py
disnake/client.py
disnake/member.py
disnake/partial_emoji.py
disnake/widget.py

Fixes an issue where you couldn't fetch the emoji data of an `Activity`/`CustomActivity` due to a missing `ConnectionState`.

fix: pass connection state to activity emoji

---

disnake/state.py

Autosharded clients rebind guild/channel references of cached messages after reconnecting to avoid keeping references to old/outdated objects, as they don't clear/recreate the caches (unlike unsharded clients). This was previously done in the `READY` handler, which generally only receives guilds in the `unavailable` state.
These guilds are effectively empty, which resulted in all cached messages' channel references being rebound to `Object`s instead of proper channels; to solve this, references will now be rebound only once all `GUILD_CREATE` events were received.

fix: rebind guilds/channels of cached messages after receiving `GUILD_CREATE` events

---

disnake/interactions/base.py
docs/api.rst

- feat: add interaction expires attributes
- fix: make InteractionMessage fallback to normal methods if the interaction is expired
closes #379
closes #459

feat: interaction expires and InteractionMessage.edit

---

disnake/guild.py

This PR prevents re-initialization of the `stage_instances` and `scheduled_events` caches on guild objects when a `GUILD_UPDATE` event is received.
This bug meant that these caches would be cleared once any guild setting was changed, effectively rendering them unusable, and has likely existed since each of these features was added.

fix: don't clear caches of stage instances and scheduled events on update

---

disnake/app_commands.py
disnake/ext/commands/converter.py

Adds support for `ApplicationCommandInteraction` to `commands.UserConverter` and `.MemberConverter`. While slash commands don't use these converters and instead use the builtin option type, these converters may still be called manually.
<sup>Also improves the `channel_types` error message, which is somewhat but not really related. I just didn't feel like opening a separate PR for a change of a few characters</sup>

fix: support interactions in `UserConverter`/`MemberConverter`

---

disnake/abc.py
disnake/audit_logs.py
disnake/ext/commands/context.py
disnake/ext/commands/core.py
disnake/ext/tasks/__init__.py
disnake/file.py
disnake/flags.py
disnake/guild.py
disnake/invite.py
disnake/member.py
disnake/message.py
disnake/permissions.py
disnake/ui/select.py
disnake/utils.py

Fixes `DeprecationWarning: invalid escape sequence` warnings as seen e.g. in the `Run pytest` step of [this](https://github.com/DisnakeDev/disnake/runs/5711479026?check_suite_focus=true) workflow run.
The resulting documentation should be exactly the same, diffing the built docs of the master branch and this branch showed no changes.
(the table in `invite.py` unfortunately looks kinda borked, but it's correct after interpreting escaped chars)

docs: fix `invalid escape sequence` warnings

---

disnake/appinfo.py
disnake/channel.py
disnake/ext/commands/base_core.py
disnake/ext/commands/ctx_menus_core.py
disnake/ext/commands/params.py
disnake/ext/commands/slash_core.py
disnake/interactions/application_command.py
disnake/interactions/base.py
docs/api.rst
docs/ext/commands/api.rst

- adds previously missing `application_command` and `command_failed` attributes to `ApplicationCommandInteraction` docs
- adds `qualified_name` to `InvokableApplicationCommand` (+ subclasses) docs
- adds `:inherited-members:` to `InteractionMessage`
- fixes missing `InstallParams` docs and broken `versionadded` directive
- adds `disnake.ext.commands.option_enum`

docs: fix several missing/broken entries

---

disnake/message.py
disnake/state.py

followup to #424
Some profiling showed that there are more references that weren't being updated when a shard reconnects, namely `message.author.guild` (in `_state._messages`), `voice_client.channel` (`_state._voice_clients`), and `message.author` (`_state._messages`, if guild chunking is enabled).
Example: in this image, `message.guild` was correctly updated to the new object (right) after reconnecting, while `message.author.guild` is the only reference to the previous guild object (left), keeping that guild and everything associated with it in memory until the message gets removed from the message cache

fix: rebind additional cached references on shard reconnect

---

disnake/http.py
docs/intents.rst

Adds a workaround for api v9 to be used instead of api v10. Intentionally, this is undocumented and is for verified bots that have not yet been granted the message content intent. This will be removed after api v10 becomes stable, and the message content intent is required, whichever comes last.

chore: add workaround for missing message content intent

---

disnake/guild_scheduled_event.py
disnake/iterators.py

pretty self-explanatory; `GuildScheduledEvent.fetch_users` no longer returns a list of (the first 100) users, but an async iterator which automatically paginates the entire event subscriber list.
Breaking change since the return type as well as parameter names/types changed.

feat!: rewrite `GuildScheduledEvent.fetch_users` to be an async iterator

---

disnake/app_commands.py
disnake/ext/commands/slash_core.py

Changes the slash command/option validation to raise an `InvalidArgument` exception instead of asserting.
Also removes the automatic `.lower()` calls on slash command and option names, which has led to bugs in the past, but that also makes this a breaking change.

fix!: improve validation of application command/option names

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
README.md
disnake/guild.py
docs/conf.py

Discord recently verified our server, so without concern of losing our vanity, we are now safe to update all invites to https://discord.gg/disnake

chore: update invite link to vanity invite

---

disnake/app_commands.py
disnake/ext/commands/interaction_bot_base.py

Adds `__str__` to `ApplicationCommand`, previously only implemented for `SlashCommand` while the other types would fall back to `__repr__`.
This is purely a cosmetic fix, and prevents this from happening with command sync debugging:
```py
COMMANDS IN 1234
===============================
| Update is required: False
| To upsert:
|     -
| To edit:
|     -
| To delete:
|     -
| No changes:
|     <SlashCommand name='localized_command'>
|     <SlashCommand name='localized_top_level'>
|     <MessageCommand name='Localized Reverse' default_permission=True>
```
(note the `default_permission` being shown)

fix: add `__str__` to `ApplicationCommand`

---

disnake/webhook/async_.py
disnake/webhook/sync.py

this exists in http.py, but not for webhook handling.
as its very useful for debugging... it should be in webhook handling too

feat(debug): add logging of what was sent to a webhook

---

disnake/types/interactions.py

this only affects users who may use these files during runtime

fix: make disnake.types.interactions importable at runtime

---

disnake/guild.py

adds ability to create a news channel
this is just a boolean parameter to create_text_channel called `news`

feat: ability to create news channels

---

disnake/member.py

adds `Member.role_icon` which shows the member's rendered icon

feat: add Member.role_icon property to display rendered role icon

---

disnake/player.py

Sometimes the execution of the cleanup function can take a few seconds which can cause a notifiable delay before the call of the `after` function. 
The idea is to call the `after` function in `player.py` before.

fix: audio delay when calling after

---

disnake/channel.py
disnake/threads.py

followup to #504
- `ForumChannel.create_thread` now returns a namedtuple instead of a plain tuple
- `Thread.__repr__` uses `{self.parent!r}` instead of `{self.parent}`, since the latter only shows the channel name

feat: return namedtuple from `ForumChannel.create_thread`, improve `Thread` repr

---

disnake/interactions/base.py

small update of typehints and documentation of defer handling,
and make it a bit more clear how it works.
code is directly taken from #474, but was removed to lower feature creep.

feat!: raise error instead of silently returning on interactions that do not support deferring

---

disnake/ext/commands/slash_core.py

Decorator-based autocompleters failed because of a bug introduced in #501 (my bad 😭) because the autocomplete function would be copied but not updated with the new slash command instance. To fix this, we now manually overwrite them inside `_ensure_assignment_on_copy`.

fix: decorator-based autocompleters

---

disnake/ext/commands/ctx_menus_core.py
disnake/ext/commands/interaction_bot_base.py
disnake/ext/commands/slash_core.py
docs/ext/commands/additional_info.rst
docs/ext/commands/slash_commands.rst
examples/context_menus/basic_contexts_menus.py

Now that commands/backend v2 appears to be rolled out for the most part, the disclaimers about registration of global commands taking up to an hour to propagate can be removed.
Keeping this as a draft while not all clients are able to access backend v2, mainly android stable.

docs: update documentation to match new backend v2 behavior

---

docs/_static/custom.js
setup.py

Updates Sphinx to 4.5.0, and removes the `/` search hotkey handler since Sphinx supports it as of sphinx-doc/sphinx@799385f5558a888d1a143bf703d06b66d6717fe4.

docs(deps): update sphinx to v4.5

---

disnake/app_commands.py
disnake/ext/commands/base_core.py
disnake/ext/commands/ctx_menus_core.py
disnake/ext/commands/slash_core.py

`bool` values for `default_member_permissions` pass type checks due to `bool` being a subtype of `int`. As this will result in issues further down the line, it now raises an exception instead.
Fixes #517.

fix: handle bool values for `default_member_permissions`

---

docs/conf.py

see https://github.com/psf/requests/issues/6140#issuecomment-1135071992
https://readthedocs.org/projects/disnake/builds/16991675/ (last step)
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.python-requests.org/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.SSLError'>: HTTPSConnectionPool(host='docs.python-requests.org', port=443): Max retries exceeded with url: /en/latest/objects.inv (Caused by SSLError(CertificateError("hostname 'docs.python-requests.org' doesn't match either of '*.ispapi.net', 'ispapi.net'")))
...
/home/docs/checkouts/readthedocs.org/user_builds/disnake/checkouts/529/docs/faq.rst:56: WARNING: unknown document: req:index
/home/docs/checkouts/readthedocs.org/user_builds/disnake/chec …
```

fix: update intersphinx link for requests

---

disnake/guild.py

The `VIP_REGIONS` feature gives guilds access to 384kbps vc, which corresponds to boost level 3 instead of 1.

fix: update `Guild.bitrate_limit` to use correct value for `VIP_REGIONS`

---

docs/ext/commands/slash_commands.rst

docs: fix broken `Range` references

---

disnake/guild.py
disnake/iterators.py

Noticed two bugs while refactoring parts of the code. They are not an issue anymore in the upcoming refactor, but having a separate fix makes it easier to backport to older versions.
- guild iterator
- Only use `before` strategy if `before` parameter was specified
- Don't stop after first page if `limit=None` is set
- Always return results in correct order
- scheduled event user iterator
- Fix missing import

fix: update guild iterator + scheduled event user iterator

---

.github/ISSUE_TEMPLATE/bug_report.yml

makes the System Information field render as a codeblock.
I don't really care what language is chosen, this is just to make it not be a codeblock. We could likely provide an empty language and it would work.

fix: make system info render in a codeblock in github issues

---

disnake/audit_logs.py
docs/api.rst

Updates the `type` field handling for audit logs, which would previously return a `ChannelType` value for webhook, integration, and permission overwrite changes.

fix: handle other `type` field types in audit logs

---

disnake/abc.py
disnake/ext/commands/context.py
disnake/ext/commands/converter.py
disnake/guild.py
disnake/interactions/base.py
disnake/message.py
disnake/state.py

Small internal improvement to guild channel typing by introducing `GuildMessageable` as a type alias of `TextChannel | VoiceChannel | Thread`. Also adds `VoiceChannel` to the `message.channel` documentation.
required by #530

typing: improve guild channel typing

---

disnake/abc.py
disnake/app_commands.py
disnake/asset.py
disnake/channel.py
disnake/client.py
disnake/errors.py
disnake/gateway.py
disnake/guild.py
disnake/http.py
disnake/integrations.py
disnake/message.py
disnake/opus.py
disnake/partial_emoji.py
disnake/reaction.py
disnake/role.py
disnake/shard.py
disnake/stage_instance.py
disnake/template.py
disnake/user.py
disnake/utils.py
disnake/webhook/async_.py
disnake/webhook/sync.py
docs/api.rst

we used these all over anyways, rather than have two kinds of exceptions
this standardizes it to TypeError and ValueError

feat!: replace InvalidArgument with TypeError and ValueError

---

disnake/interactions/application_command.py
disnake/interactions/message.py
disnake/interactions/modal.py

makes interaction data available before the data objects have been
modified to add data as a property or attribute

fix: make interaction data dataclasses dicts

---

disnake/guild_scheduled_event.py

Adds `GuildScheduledEvent.created_at` and `.url`, and addresses some minor documentation issues.

feat: add `GuildScheduledEvent.created_at` and `.url` properties

---

disnake/guild.py
disnake/guild_scheduled_event.py

Replaces `ValueError`s used for invalid parameter types with `TypeError`s in `Guild.create_scheduled_event` and `GuildScheduledEvent.edit`.

fix!: raise `TypeError` instead of `ValueError` in scheduled events validation

---

disnake/components.py
disnake/errors.py
disnake/ext/commands/bot_base.py
disnake/ext/commands/converter.py
disnake/ext/commands/core.py
disnake/ext/commands/view.py
disnake/iterators.py
disnake/ui/action_row.py
disnake/widget.py
docs/conf.py
requirements/requirements_dev.txt
tests/ext/commands/test_core.py

Updates pyright from 1.1.245 to .254, and fixes the 27 new type-checking errors caused by the version bump.

typing: update pyright to 1.1.254, fix new errors

---

disnake/ext/commands/base_core.py
disnake/ext/commands/interaction_bot_base.py
disnake/ext/commands/params.py
disnake/ui/button.py
disnake/ui/item.py
disnake/ui/select.py

- Add generic parameters to user/message command decorators in `InteractionBotBase`, similar to #514
- Update `Param` default parameter type to improve compatibility with callable/dynamic defaults
- Fix view typevar in ui items by using `Optional[View]` bound instead of `View, None` constraints
some changes were originally part of #519, but now split to avoid additional scope creep

typing: update command decorators, fix item typevar bounds

---

disnake/gateway.py
disnake/types/gateway.py

Removes the `$` prefix from ws identify properties. The old field names still work, but are deprecated.
ref: https://github.com/discord/discord-api-docs/pull/5058

fix: update identify properties

---

disnake/abc.py
disnake/enums.py

Fixes `channel.edit(default_auto_archive_duration=ThreadArchiveDuration.hour)` which should be supported according to type hints but instead resulted in `TypeError: Type is not JSON serializable: _EnumValueBase_ThreadArchiveDuration`

fix: handle `default_auto_archive_duration` enum value in channel edits

---

disnake/guild.py

Currently ``Guild.invites`` is unclear as to whether or not it also returns the Guilds vanity invite in applicable guilds, this PR aims to clear that up.

docs: make guild invite documentation clearer regarding vanity invites

---

disnake/interactions/message.py
disnake/interactions/modal.py
disnake/types/interactions.py

Refactors modal interaction component typings which previously used full `ActionRow` types instead of partial types like the ones that are actually received in interactions.
`ModalInteractionData.[_]components` is now no longer a `List[ActionRow]` with mostly empty components, and instead just the raw data dict from the interaction, which avoids discarding currently unused data (like select values). This is unfortunately a breaking change, but necessary as the old typing was mostly wrong and could've resulted in issues with component parsing code due to missing fields.
- *renamed `_components` to `components`, changed type*
- *renamed `walk_components` to `walk_raw_components`*

fix!: improve interaction component typings

---

disnake/ext/commands/params.py
tests/ext/commands/test_params.py

Fixes #577.
An annotation like `Union[User, Member]` passes the `issubclass_(self.type, disnake.Member)` check since `issubclass_` explicitly handles unions; the following `isinstance(argument, disnake.Member)` check did not accept `User` objects, even though they should've been permitted based on the annotation type.
This PR improves the validation logic to correctly handle cases like this as well.
Regression from #283 - third test case of `test_verify_type` checks for this particular one.

fix: correctly handle unions in `verify_type`

---

disnake/app_commands.py
disnake/ext/commands/params.py
disnake/ext/mypy_plugin/__init__.py
disnake/types/interactions.py
docs/ext/commands/api.rst
docs/ext/commands/slash_commands.rst

implements https://github.com/discord/discord-api-docs/commit/1159aef52648602c22f72104faaed0155fafca64

feat: string option length limits

---

disnake/components.py
disnake/interactions/modal.py
disnake/ui/action_row.py
examples/modal.py
tests/ui/test_action_row.py

Reverts #558 which was merged prematurely.
Support is not guaranteed on all platforms and the API may not be finalized yet, so it's better to keep this implementation in a draft state for now while details are still being worked on.

revert: "feat: support selects in modals (#558)"

---

.github/workflows/lint-test.yml

we don't have coveralls configured to comment
plus this is not ideal for action concurrency limits
so we add the concurrency rule to pytest

ci: don't run tests on the pull context if on main repo

---

disnake/ext/commands/params.py
docs/ext/commands/slash_commands.rst
tests/ext/commands/test_params.py

Adds support for `Union[User, Role]` and `Union[User, Member, Role]` in slash commands, which correspond to `OptionType.mentionable`.

feat: support additional union types for mentionable parameters

---

disnake/mentions.py
tests/test_mentions.py

superseeds #592 
closes #573
Add `AllowedMentions.from_message()` which creates an AllowedMentions from a message's current state.

feat: add AllowedMentions.from_message

---

disnake/opus.py

Fixes "invalid argument" errors when attempting to encode/decode Opus on M1 Macs. See: https://github.com/Rapptz/discord.py/commit/bd637e2462697e32098efdaa314489631e215f20

Fix opus on macos arm64

---

changelog/605.feature.rst
disnake/flags.py
disnake/permissions.py

Adds `&`, `|`, `^`, `~`, `<`, `<=`, `>`, and `>=` support to flags.

feat: add more operators to flags

---

.github/workflows/check-pull-labels.yaml

If the check is skipped entirely, it'll be stuck as "pending" if another commit is pushed without changing labels
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
regression from #600

ci: run check-pull-labels on synchronize

---

noxfile.py

Adds a confirmation prompt when running `task setup_env`/`nox -s setup` outside of a virtual environment, which is generally not recommended.

feat: check for venv before installing dependencies in nox setup

---

changelog/528.feature.rst
disnake/app_commands.py
disnake/ext/commands/ctx_menus_core.py
disnake/ext/commands/interaction_bot_base.py
disnake/ext/commands/slash_core.py
disnake/types/interactions.py

Setting `nsfw=True` disables/hides a command outside of nsfw channels - like many other fields, it cannot be set per subcommand or group.
Not announced/documented yet and support in DMs is still tbd/wip, hence the draft PR.

feat: add nsfw field to application commands

---

docs/_static/style.css

Fixes an issue where on some screens the footer was being clipped by the navigation tree and wasn't fully visible

fix(docs): float the footer when it clips the nav aside

---

changelog/575.bugfix.rst
disnake/ext/commands/cog.py

Fixes #575.
Previously, accessing `self.<command_name>` in a cog would return the old/original command object, not the copied one, which resulted in a few issues.
This applies a fix that's effectively the same as what prefix commands were already doing.

fix: replace old command objects in cogs with new copies

---

changelog/651.misc.rst
disnake/ext/commands/converter.py
disnake/ext/commands/help.py
disnake/message.py
disnake/partial_emoji.py
disnake/utils.py
disnake/webhook/async_.py
disnake/webhook/sync.py

The oldest ID is 17 characters, and 20 digit IDs won't be around for decades (if ever)
Gets rid of ID regexes checking for 15 character IDs, and switches to a max of 19 characters because that's the maximum ID length for the foreseeable future.

refactor: standardize id regex to {17,19}

---

changelog/642.feature.rst
disnake/abc.py
disnake/channel.py
disnake/threads.py

```py
await channel.edit(flags=disnake.ChannelFlags(pinned=True)
```

feat: allow setting ChannelFlags directly when editing a channel or thread

---

CONTRIBUTING.md
changelog/README.rst

Fix the broken link in CONTRIBUTING.md, plus a few formatting issues in changelog/README.rst

chore(docs): replace broken links and formatting in contributing documentation

---

disnake/activity.py
disnake/components.py
disnake/ext/commands/help.py
disnake/http.py
disnake/member.py
disnake/partial_emoji.py
pyproject.toml
requirements/requirements_dev.txt

- Update pyright from 1.1.258 to 1.1.264 (slowdowns and minor bugs as seen in .262 seem to be fixed)
- Instead of using `basic` mode and enabling a bunch of rules, use `strict` mode and disable those we (currently) don't want
- Enable `strictListInference`, `strictDictionaryInference`, and `strictSetInference` rules

typing: update pyright, reconfigure rules

---

docs/whats_new.rst

Port the changelog from v2.4.1 to the default branch so it shows up on the latest docs. 
Also added a small line about the changes being backports from v2.6.0 (which is currently unreleased).

docs: port changelog from v2.4.1

---

docs/whats_new.rst

Port the changelog from v2.5.2 to the default branch so it shows up on the latest docs. 
Also added a small line about the changes being backports from v2.6.0 (which is currently unreleased).

docs: port changelog from v2.5.2

---

requirements/requirements_dev.txt

Fixes slotscheck issue on Python 3.10 - [changelog](https://github.com/ariebovenberg/slotscheck/blob/main/CHANGELOG.rst#0150-2022-08-09).
<details>
<summary>slotscheck 0.14.0/0.15.0 runs</summary>
```py
$ python -V
Python 3.10.4
$ nox -s slotscheck
nox > Running session slotscheck
nox > Re-using existing virtual environment at .nox/slotscheck.
nox > python -m pip install -U -r requirements.txt -r requirements/requirements_dev.txt
nox > python -m slotscheck --verbose -m disnake
ERROR: 'disnake.utils:SnowflakeList' has slots but superclass does not.
Superclasses without slots:
- 'array:array'
Oh no, found some problems!
stats:
modules:     102
checked:   75
excluded:  27
skipped:   0
classes:     342
has slots: 157
no slots:  185
n/a:       0
nox > Command python -m slotscheck --verbose -m …
```

build(deps): update slotscheck to 0.15.0

---

.flake8

Adds per-file ignores for `S311` ("Standard pseudo-random generators are not suitable for security/cryptographic purposes.").
As far as I can tell, bandit should disallow `random.Random` on all platforms, however it currently only does so on Windows (the only platform where fnmatch is case-insensitive), see https://github.com/PyCQA/bandit/issues/926.
This means that:
- adding `# noqa: S311` to the affected lines won't work, as flake8-noqa would complain about an unnecessary noqa on macOS/Linux
- but not ignoring these `S311` results in them being shown as errors on Windows
It's a fairly minor issue, but it does make contributing on Windows slightly more annoying.

fix(lint): ignore S311 due to flake8/bandit bug

---

changelog/689.bugfix.rst
changelog/689.deprecate.rst
changelog/689.doc.rst
disnake/ext/commands/bot.py
disnake/ext/commands/bot_base.py

Shows a deprecation warning instead of message content intent warning when using `Bot(command_prefix=None)`, and improves the docs regarding `None` prefixes.
Resolves #688.

fix: check for `command_prefix=None` before warning about message content intent

---

.flake8
.pre-commit-config.yaml
changelog/590.breaking.rst
changelog/615.feature.rst
changelog/648.doc.rst

This removes the two symlinks currently present in the repo that are being used for linking related issue/PR IDs in the changelog. Since symlinks generally don't work on Windows, we unfortunately have to get rid of them as they'll make contributing more difficult.
Instead, these files that were previously symlinks now just have the same content as the files they were linking to, leading to the same result in the built changelog (as towncrier groups entries based on content). While this isn't a great solution, it's the only one (short of forking towncrier), as there isn't any way of hooking into the changelog generation process.
Also adds a pre-commit hook that prevents symlinks from being committed to the repo in the future.

fix(docs): remove symlinks, update lint config

---

changelog/702.misc.rst
requirements/requirements_speed.txt

Limits the installation of `cchardet` to Python versions 3.9 and below, mirroring the aiohttp change https://github.com/aio-libs/aiohttp/pull/6857.
While `cchardet` appears to work fine on 3.10, it's been unmaintained for more than a year, and as such there are no wheels built for versions newer than 3.9. This breaks the install of the `[speed]` extra on systems using 3.10 without build tools.

deps: don't install cchardet on py >3.9

---

changelog/690.misc.rst
docs/extensions/attributetable.py
docs/extensions/builder.py
docs/extensions/exception_hierarchy.py
docs/extensions/nitpick_file_ignorer.py
docs/extensions/resourcelinks.py
noxfile.py

This allows `sphinx-build -j` to run faster by enabling parallel reads, which are not enabled by default (unlike parallel writes).
For these options to take effect they must be supported by *all* extensions, which is the case for all the other builtin and external extensions we're using.
See https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata.
Things to be considered:
- We'd have to make sure all our versions have this PR merged. or are at least not set to fail on warning.
```sh
(master) $ time nox -Rs docs --non-interactive
real    0m47.710s
user    0m47.089s
sys     0m0.639s
(master) $ time nox -Rs docs --non-interactive -- -j8
real    0m51.056s
user    0m51.076s
sys     0m0.879s
(fix/docs-parallel) $ time nox -Rs docs --non-interactive
real    0m47.869s
user …
```

fix(docs): enable `parallel_read_safe` for all sphinx extensions

---

changelog/698.feature.rst
disnake/audit_logs.py
disnake/automod.py
disnake/enums.py
disnake/guild.py
disnake/types/automod.py
docs/api.rst

- Add `AutoModTriggerType.mention_spam` with its corresponding `AutoModTriggerMetadata.mention_total_limit` field
- Add missing `AuditLogAction.automod_send_alert_message` and `.automod_timeout` action types - not documented yet, but they've been around for a while (June 30th) and presumably are stable
ref: https://github.com/discord/discord-api-docs/pull/5212

feat(automod): add mention spam type and new audit log action types

---

.pre-commit-config.yaml

as mentioned in #700, validates changelog entries end with `.rst` and start with numbers

lint: validate changelog names start with numbers and end with rst

---

changelog/711.doc.rst
docs/ext/commands/slash_commands.rst

Application command localizations just rolled out today to all platforms (except the "old" Android client): https://canary.discord.com/channels/613425648685547541/697138785317814292/1009201109967052851

docs: remove note about appcmd localizations build override

---

changelog/653.bugfix.rst
disnake/app_commands.py

fix: check the type of the name when validating slash command and option names

---

changelog/705.bugfix.rst
disnake/guild.py

fix!: persist other features when changing the community feature

---

changelog/720.doc.rst
disnake/guild.py

docs: remove references to public guilds and refer to them as community

---

disnake/flags.py

backport to fix Intents.all() and Intents.default() providing the message content intent when they shouldn't.

fix: don't provide message content intent with Intents.all()

---

changelog/729.feature.rst
disnake/integrations.py
disnake/types/integration.py

see https://github.com/discord/discord-api-docs/pull/5311

feat: add `BotIntegration.scopes`

---

disnake/abc.py

implements discord/discord-api-docs/pull/5435
depends on discord/discord-api-docs/pull/5435 being merged, too 🙃

docs: document that messages can be sent with only components

---

changelog/738.feature.rst
disnake/errors.py
disnake/interactions/base.py
docs/api.rst
test_bot/cogs/guild_scheduled_events.py

start to shift original_message to original_response, but keep the old names around for quite a while.

feat: alias original_message methods to original_response to be less confusing

---

changelog/740.feature.rst
disnake/ui/action_row.py

same as #733 but for action rows (suggested in [this comment](https://github.com/DisnakeDev/disnake/pull/733#issuecomment-1241973146) by @shiftinv)

feat: return self in actionrow row methods to allow chaining calls

---

changelog/744.misc.rst
disnake/ui/action_row.py
disnake/ui/select.py

Previous annotations didn't allow calls like `row.add_select(options=["a", "b"])`, full `SelectOption` instances had to be provided even though the underlying code supports both.

typing: update options parameter type in `ui.ActionRow.add_select`

---

changelog/745.doc.rst
disnake/threads.py

Unlike threads in text channels, it seems like forum threads can be deleted by the owner without `manage_threads` perms if there are no replies, i.e. only the initial message (or none) exists in the thread.

docs: own forum threads can be deleted if there are no replies

---

changelog/746.bugfix.rst
disnake/channel.py

Without `manage_messages` perms, trying to create a thread in a forum channel currently results in a permissions error, as the client always sends the `slowmode_delay`/`rate_limit_per_user` field in the request (defaulting to 0).
This PR fixes that by only sending the field if necessary, and additionally removes the `type` field which isn't documented (but works fine nonetheless, and was required in initial stages of the forums API iirc).

fix: only send `slowmode_delay` param with `ForumChannel.create_thread` if required

---

disnake/ext/commands/core.py
disnake/ext/tasks/__init__.py
disnake/i18n.py
disnake/ui/item.py
requirements/requirements_dev.txt

The `# type: ignore` in `Localized.__init__` is due to `strictParameterNoneValue` still being disabled, all the other changes take care of valid typing errors that were previously false negatives.

deps: bump pyright to 1.1.271

---

changelog/749.doc.rst
disnake/flags.py
disnake/permissions.py
tests/test_flags.py
tests/test_permissions.py

Resolves #607.
The description in that issue isn't fully correct, essentially it boils down to "later kwargs take precedence over earlier kwargs".

docs: clarify behavior of flag initializer kwargs with aliases

---

changelog/747.bugfix.rst
disnake/state.py

Followup to #730.
It appears that the message type of the initial forum thread message isn't `thread_starter_message (21)`, but just `default (0)`.
We relied on the message type to accurately update the message count fields, which means it's now off by one for newly created forum threads.
This PR instead mirrors the internal client behavior by also checking the message ID, see the comments in the code.

fix: don't count initial message in forum threads towards `message_count`

---

changelog/757.feature.rst
disnake/automod.py

renames ``with_edits`` to ``with_changes`` for less confusion.

feat: rename with_edits to with_changes

---

docs/api.rst

The documentation of `Interaction` subclasses still shows documentation for `original_message`, which is particularly confusing as it also contains the `.. versionchanged` that only makes sense in the context of `original_response`.
This pr properly documents them as aliases, which could then be deprecated in the near future.

docs: fix outdated inherited `original_message` aliases

---

changelog/435.breaking.rst
changelog/435.deprecate.rst
changelog/768.deprecate.rst
disnake/embeds.py
docs/conf.py
tests/test_embeds.py

Followup to #435, makes it a less breaking change.
`EmptyEmbed` and `Embed.Empty` emit deprecation warnings at runtime, and are gated behind `if not TYPE_CHECKING:` to generate type-checking errors already while keeping runtime behavior for now.

feat: add backwards-compatible `EmptyEmbed` alias

---

changelog/769.feature.rst
disnake/gateway.py

Since we only get the `resume_gateway_url` in the `IDENTIFY`, and don't receive it again when resuming, the value was lost after the first resume, resulting in all subsequent resumes connecting to the initial gateway again:
1. initial connect to `gateway.~`, receive and store resume url (e.g. `gateway-us-east1-c.~`)
1. resume to `gateway-us-east1-c.~`, no resume url received and stored value is lost since the ws is recreated every time
1. resume to `gateway.~`, since we don't have a resume url
1. resume to `gateway.~`
1. ...
This PR fixes this behavior by storing the current url (e.g. `gateway-us-east1-c.~` in 2.) as the resume url, changing the flow to this:
1. initial connect to `gateway.~`, receive and store resume url (e.g. `gateway-us-east1-c.~`)
1. resume to `gateway-us-east1-c.~`, …

fix(gateway): default to current url for resuming instead of initial url

---

changelog/770.bugfix.rst
disnake/ext/commands/params.py

Fixes edge case in annotation parser.
Previously it would call `issubclass` with a non-type parameter for particular command annotations, e.g.
```py
from typing import Literal, Optional
import disnake
from disnake.ext import commands
bot = commands.Bot()
async def f(inter: disnake.CommandInteraction, stuff: Optional[Literal[1, 2, 3]] = None):
...
```

fix: handle edge case with `Optional[Literal[...]]` parameter annotations

---

.github/workflows/lint-test.yml

was an invalid command before.

fix(ci): typo in codemod error message on GHA

---

MANIFEST.in
changelog/784.misc.0.rst
changelog/784.misc.1.rst

https://peps.python.org/pep-0561/#packaging-type-information
> For namespace packages (see [PEP 420](https://peps.python.org/pep-0420)), the `py.typed` file should be in the submodules of the namespace, to avoid conflicts and for clarity.

fix: add missing py.typed markers to namespace packages

---

disnake/shard.py

hides the second overload using NoReturn; typecheckers won't use it because of that.
Not sure if this is a feature or a bug with type checkers, tho :)

feat: hide the extra disnake.AutoShardedClient overload in typechecking

---

changelog/766.breaking.rst
changelog/766.feature.rst
disnake/message.py

fixes an issue where system_content could potentially be None even when documented as returning a string in all cases.
Additionally updates the strings to the latest strings from the client. There's a few cases which have questions which are current documented as comments, and I was not sure about app commands and context menu commands. 
This pr is waiting on having the above questions answered before documentation and changelogs are added.

fix: update system_content with updated strings and always return str

---

changelog/793.doc.rst
disnake/appinfo.py
disnake/automod.py
disnake/embeds.py
disnake/guild.py
disnake/raw_models.py
disnake/types/activity.py
disnake/types/gateway.py
disnake/voice_client.py
docs/api.rst
docs/conf.py

Adds a `:ddocs:` role for easily linking to `https://discord.com/developers/docs/*`, and fixes a couple invalid links that are a result of api docs changes.
Also adds a `linkcheck_ignore` config for running the linkcheck builder without making unnecessary requests. This is meant to be run manually and hence I didn't integrate linkcheck into the ci workflow, mainly because (1) there really isn't a point in doing this every time, and (2) checking fragments/anchors for api docs isn't possible since the entire page is generated dynamically.

docs: add Discord docs extlinks entry, update broken links

---

changelog/792.bugfix.rst
disnake/embeds.py
tests/test_embeds.py

Copies the `_fields` list in `Embed.copy()` and prevents updating fields of the original embed through a copied one.
Previously, this would have passed:
```py
e = Embed()
assert e._fields is e.copy()._fields
```
Note that this PR uses a shallow copy of the `_fields` list, not a deep copy.
As such, `e._fields[0] is copy._fields[0]` still holds, which shouldn't be an issue as the field elements are not mutable through `e.fields` (which returns `list[EmbedProxy]` instead of the underlying `list[dict]`).
This also does not handle `Embed.from_dict(e.to_dict())`, which still retains those references as before, as it's not meant for copying and can result in a variety of problems if used for that purpose - `Embed.copy` takes care of those, it exists for a reason :^)
see …

fix: ensure embed fields are copied properly

---

disnake/components.py
disnake/ui/action_row.py
disnake/ui/button.py
disnake/ui/select/string.py
disnake/ui/view.py
disnake/utils.py

Some minor internal typing and documentation changes, like adding a couple `assert_never`s in component factory methods.

typing: misc internal component typing changes

---

changelog/797.doc.rst
docs/404.rst
docs/conf.py
requirements/requirements_docs.txt

adds a custom 404 page to the documentation

docs: custom 404 page

---

docs/_templates/layout.html

The recent material-icons pr accidentally changed the sidebar spacing due to changing the order of the font css (which caused the priority of rules in style.css to go beneath the defaults, disabling them). This fixes that

docs: fix spacing issue due to the reordering of material icons css

---

changelog/810.bugfix.rst
disnake/member.py

The `Member.ban` method was providing a default to clean_duration
which causes an issue when anyone attempts to use
`delete_message_days`, essentially *not* including a deprecation
period for `delete_message_days`. This simply removes the default of
86400 seconds as that default is already provided in the `Guild.ban`
method, which is used internally by `Member.ban`.

fix: don't provide a default clean history duration as that makes the delete_message_days parameter unusable

---

changelog/810.bugfix.rst
disnake/member.py

backport of dd4643bf03d4179e6a61afb8a31c8e10e45facc3
The `Member.ban` method was providing a default to clean_duration which causes an issue when anyone attempts to use
`delete_message_days`, essentially *not* including a deprecation period for `delete_message_days`. This simply removes the default of 86400 seconds as that default is already provided in the `Guild.ban` method, which is used internally by `Member.ban`.

backport(2.6): don't provide a default clean history duration in `Member.ban` 

---

changelog/792.bugfix.rst
disnake/embeds.py
tests/test_embeds.py

backport(2.6): ensure embed fields are copied properly

---

.github/actions/setup-env/action.yml
.github/workflows/lint-test.yml

Updates `actions/setup-python` to v4, as GitHub recently deprecated `::save-state` and `::set-output`:
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
pip also started emitting deprecation warnings for legacy builds, which as far as I know is resolved by just installing `wheel`:
> DEPRECATION: livereload is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option.

ci: update actions/packages to avoid deprecation warnings

---

changelog/816.feature.rst
disnake/interactions/base.py
disnake/webhook/async_.py

The API recently started supporting `DELETE /webhooks/.../@original`; `inter.delete_original_response()` already works fine, however `inter.response.send_message(delete_after=)` didn't.
Not sure if this should be considered a bugfix instead of a feature.

feat: support `delete_after` for ephemeral messages

---

changelog/820.bugfix.rst
disnake/flags.py

Somehow missed this while testing, probably when `ListBaseFlags` got refactored. The API expects `1, 2, 3`, while the library would previously use `0, 1, 2` instead.

fix: fix off-by-one error in `AutoModKeywordPresets`

---

changelog/818.bugfix.rst
disnake/channel.py
disnake/http.py
disnake/message.py

#746 2: electric boogaloo
It appears that text channels now support `default_thread_rate_limit_per_user` like forum channels (which, funnily enough, is documented in the api docs, since it was incorrectly documented initially and never removed).
This API change unfortunately breaks `channel.create_thread`/`message.create_thread` without `manage_threads` permissions, when the parent channel's `default_thread_rate_limit_per_user` is not `0`. Instead of sending `rate_limit_per_user: 0` by default, we want to inherit the parent's value now.

fix: only send `rate_limit_per_user` parameter on thread creation if required

---

changelog/825.bugfix.rst
disnake/ext/commands/core.py

prevents optional variadic arguments (*args: Optional[str]) from being stuck in infinite loops in specific cases.

fix: optional variadic arguments no longer can be stuck in infinite loops

---

changelog/832.feature.rst
disnake/interactions/base.py

implements https://github.com/discord/discord-api-docs/issues/4784
followup to #474

feat: allow suppressing embeds when editing an interaction response

---

disnake/ext/commands/flag_converter.py
disnake/utils.py

Testing 3.11 in one of my bots, I noticed the same dataclass error in my code that previously appeared in `commands.Flag`.
`MISSING` is used outside of this project too (even if it may be undocumented), this PR improves compatibility further.
An alternative to `0` would be returning `id(self)`, but since `MISSING` is meant to be a singleton (and hash collisions wouldn't matter even if it wasn't), using a constant is fine too.
(somewhat of a followup to #785)

feat: add `_MissingSentinel.__hash__`

---

changelog/800.feature.rst
changelog/803.feature.rst
disnake/components.py
disnake/enums.py
disnake/interactions/base.py
disnake/interactions/message.py
disnake/state.py
disnake/types/components.py
disnake/types/interactions.py
disnake/ui/action_row.py
disnake/ui/item.py
disnake/ui/select/__init__.py
disnake/ui/select/base.py
disnake/ui/select/channel.py
disnake/ui/select/mentionable.py
disnake/ui/select/role.py
disnake/ui/select/string.py
disnake/ui/select/user.py
disnake/ui/view.py
docs/api.rst
examples/interactions/low_level_components.py
examples/views/select/dropdown.py
tests/ui/test_action_row.py
tests/ui/test_decorators.py

Adds new select menu components/items, with <sup><sub>almost</sub></sup> everything there is to it (component types, methods, decorators, ...).
This is a draft PR for several reasons:
- ~~It depends on #800, which is currently set as the base branch to get a clean diff.~~
- ~~It depends on #801, which is currently merged into this branch to avoid merge conflicts later on.~~
- ~~I haven't added backwards-compatible aliases yet, but that'll be easy enough once everything else is settled.~~
- ~~Depends on #814 for the `resolved` field, currently set as base branch.~~
- May want to consider fixing the `Select.values` issue with concurrent interactions.
Resolves #798.

feat: implement new select menu components

---

.github/workflows/lint-test.yml

Haven't investigated what exactly happened, but GitHub Actions' yaml parser (YamlDotNet?) no longer likes `.github/workflows/lint-test.yml` and spits out this fun error:
> The workflow is not valid. .github/workflows/lint-test.yml: While scanning a multi-line double-quoted scalar, found wrong indentation.
While the yaml spec apparently isn't 100% clear about it, this PR fixes the indentation to make the parser happy.

fix(ci): indent quoted multiline string

---

docs/whats_new.rst

forward port the 2.6.2 changelog
2.6.2 has not been published as of yet.

docs: forward port the 2.6.2 changelog

---

.github/workflows/lint-test.yml

as shown in the logs [here](https://github.com/DisnakeDev/disnake/actions/runs/3388788779), alls-green is using the deprecated set-output command by github, and needs to be updated.

chore: update alls-green to fix ci deprecation warnings

---

changelog/794.feature.rst
disnake/automod.py
disnake/types/automod.py

implements https://github.com/discord/discord-api-docs/pull/5504
This has been tested in a private server.

feat: support regex automod

---

changelog/872.doc.rst
disnake/channel.py
disnake/guild.py
disnake/threads.py
disnake/types/guild.py

title.
See https://github.com/discord/discord-api-docs/commit/2d24487e83ddd92c69fab0523c572f4d50a0e687; The API and client UI already reflect this change.

docs: private threads no longer require boost/guild feature

---

changelog/859.doc.rst
docs/_templates/layout.html
docs/conf.py

Adds an [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) description file to the docs:
It only registers *sometimes* in chromium-based browsers and no-one really seems to know why, I think at this point I've spent more time looking at the chromium bugtracker and other projects' GitHub issues than actually implementing this.
It works fine in Firefox (see screenshot) :shrug: 
sphinx config docs: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_use_opensearch

docs: enable opensearch

---

changelog/870.bugfix.rst
disnake/user.py

The `Message.__init__ -> Message._handle_member -> Member._from_message` path calls `User._to_minimal_user_json`, which previously didn't copy over the user's `public_flags` value.
With the member cache (and therefore also the user cache) enabled, this isn't an issue as `Member.__init__` uses the cached user and not the (previously incomplete) user data. With the cache disabled, the user data gets parsed, which didn't include that value.
To reproduce, just `print(ctx.author.public_flags)`.

fix: handle `public_flags` value for `Message.author` when member cache is disabled

---

changelog/854.feature.rst
disnake/channel.py
disnake/guild.py
disnake/message.py
disnake/types/channel.py
docs/api.rst

Similar to forum channels, this field now also works on text/announcement channels.

feat: implement `TextChannel.default_thread_slowmode_delay`

---

changelog/858.bugfix.rst
disnake/state.py
disnake/user.py

This largely reverts cb2363f0fd819ce1a5c38b42cd403fcb8994be6f.
Users were not being evicted as expected, resulting in objects being retained solely in the user cache, with no other strong references.
See https://docs.python.org/3.10/library/weakref.html#weakref.WeakValueDictionary and [https://docs.python.org/3.10/reference/datamodel.html#object.__del__](https://docs.python.org/3.10/reference/datamodel.html#object.__del__).
The difference in performance and memory usage is insignificant, at least in 3.10; haven't tested other versions, but this is a bug regardless of version.
To reproduce, anything that uses `state.store_user` can be used, for example the `GUILD_BAN_REMOVE` handler:
```py
print(bot.get_user(21414249976823808))
await ctx.guild.ban(disnake.Object(21414249976823808))
await …
```

fix: revert to weakrefs for user cache

---

requirements/requirements_dev.txt

async tests are currently [failing](https://github.com/DisnakeDev/disnake/actions/runs/3704516848) due to a change in 3.10.9/3.11.1 (released last week) that results in a deprecation warning being emitted.
This was fixed in [`pytest-asyncio 0.20.3`](https://github.com/pytest-dev/pytest-asyncio/blob/master/CHANGELOG.rst#0203-22-12-08).

fix(deps): update pytest-asyncio to fix CI failures on latest 3.10/3.11

---

changelog/903.feature.rst
disnake/channel.py

Fixes the default value of `default_layout` in `ForumChannel.edit`, which prevented editing forum channels when the parameter wasn't specified.
followup to #885
[context](https://canary.discord.com/channels/808030843078836254/1060004812135079996)

fix: change `default_layout` value from `...` to `MISSING`

---

changelog/907.bugfix.rst
disnake/client.py

`ConnectionState.delete_guild_command` was previously unused, with `Client.delete_guild_command` directly calling the http endpoint and not removing the command from the local command cache.
This is a pretty minor (and ancient) bug, and mainly resulted in `Client.get_guild_command`/`.get_guild_application_commands` possibly returning now-deleted commands.

fix: avoid stale local command cache when deleting guild application command

---

changelog/906.feature.rst
disnake/__init__.py
disnake/appinfo.py
disnake/application_role_connection.py
disnake/client.py
disnake/enums.py
disnake/http.py
disnake/role.py
disnake/types/appinfo.py
disnake/types/application_role_connection.py
disnake/types/i18n.py
disnake/types/interactions.py
disnake/types/role.py
docs/api.rst

Implements application role connection ("linked roles") metadata and `role_connections_verification_url` from https://github.com/discord/discord-api-docs/pull/5668, as well as `RoleTags.is_linked_role` from https://github.com/discord/discord-api-docs/pull/5771.
Note that the `GET/PUT /users/@me/applications/{application.id}/role-connection` route isn't implemented, since that's more on the oauth side of things.
As such, this PR supports fetching/editing the metadata configured by the bot ("guilds can require users to have some minimum number of cookies"), but evidently doesn't allow fetching/editing specific users' metadata values ("user x has y cookies").

feat: role connections

---

changelog/911.bugfix.rst
disnake/enums.py
disnake/sticker.py
disnake/types/sticker.py

The current sticker deserialization code doesn't account for unknown `format_type`s, potentially resulting in `KeyError`s when trying to parse stickers due to the file extension lookup.
The new .gif sticker format (see #910) is one such format, meaning messages sent with such a sticker will result in exceptions.
This won't result in full crashes in >=2.6, but will still prevent messages with such stickers from being handled.
Instead of computing the url at initialization, it is now essentially deferring the `KeyError` to whenever a bot tries to access `.url`; one potential future change would be to make `url` optional to account for unknown formats.

fix: fix errors when trying to deserialize stickers with unknown formats

---

docs/api.rst

Followup to #906, fixes a documentation formatting issue.

docs: fix missing spaces in `ApplicationRoleConnectionMetadataType` enum

---

docs/api.rst

Since it doesn't refers only to `on_guild_role_create` i think it's better to not use `new`; the event will be fired when deleting any `Role`, the "new" word could lead to misunderstanding.

fix wording of 'on_guild_role_create/delete'

---

changelog/920.feature.rst
disnake/audit_logs.py

The currently implemented `user` property will try to retrieve the user from the cache. If the user cannot be found, we return `None` with no way to get the user ID. Therefore a new `user_id` property has been introduced.

feat: add fallback to `Object` for user property in AuditLogEntry

---

.github/workflows/lint-test.yml
.pre-commit-config.yaml

Updating `pre-commit/action` resolves the nodejs v12 deprecation warning mentioned in #852.
This also uncovered a [dependency issue](https://github.com/DisnakeDev/disnake/actions/runs/4076273215/jobs/7023783749) with the current isort version, which would've likely come up anyway once the caches expire - see https://github.com/PyCQA/isort/issues/2077.

ci: update `pre-commit/action` and `isort`

---

changelog/912.breaking.rst
changelog/912.bugfix.rst
disnake/sticker.py
disnake/types/sticker.py

The `cover_sticker_id` and `banner_asset_id` fields in the sticker pack data are marked as optional in the [API docs
](https://discord.com/developers/docs/resources/sticker#sticker-pack-object-sticker-pack-structure), but have so far been treated as required.
This was fine in all but the latest "Snowsgiving Surprise Pack", which does not have a banner, breaking `Client.fetch_premium_sticker_packs`.

fix!: `StickerPack.cover_sticker_id` and `.banner_asset_id` are optional

---

changelog/921.bugfix.rst
disnake/client.py
disnake/http.py
disnake/shard.py
disnake/webhook/async_.py
disnake/webhook/sync.py

A couple places in the code attempt to handle connection resets by checking `OSError.errno in (54, 10054)`. This works on Windows (`10054`) and macOS/BSD (`54`), but not on Linux, where `ECONNRESET` is `104`.
Python's `errno` module makes handling this across different platforms much easier.

fix: use `errno.ECONNRESET` to handle connection resets on Linux properly

---

disnake/__init__.py

Bumps version to v2.9.0a for development.

chore: bump to 2.9.0a

---

disnake/components.py
disnake/ext/commands/converter.py
disnake/ext/commands/core.py
disnake/ext/tasks/__init__.py
disnake/interactions/base.py
requirements/requirements_dev.txt

Updates pyright from .271 to .291, fixing the new warnings in the process.
The latest version at the time of writing is .293, however due the updated `reportUnnecessaryComparison` diagnostic I'll hold off on updating to that, since it may require more work.

deps: update pyright to v1.1.291

---

.github/workflows/lint-test.yml

partially closes #819
this has the side-effect that we will no longer have ci on branches that are not linked to a pull request or a release branch

fix(ci): move concurrency rules from steps to workflow top level

---

docs/_templates/layout.html

sphinx 6 changed the path provided to the favicon slightly.

docs: update path to favicon after sphinx 6.0.1 update

---

changelog/929.feature.0.rst
changelog/929.feature.1.rst
disnake/abc.py
disnake/channel.py
disnake/flags.py
disnake/interactions/base.py
disnake/message.py
disnake/webhook/async_.py
disnake/webhook/sync.py

Adds `MessageFlags.suppress_notifications` (https://github.com/discord/discord-api-docs/pull/5910), and implements a `flags` parameter on all `send`-like methods.

feat: add `MessageFlags.suppress_notifications` and `flags` parameter

---

changelog/919.feature.rst
disnake/guild.py
disnake/http.py
disnake/iterators.py

https://github.com/discord/discord-api-docs/commit/38f01b07531b672880e434692d215233e45eb0db
This was removed in #473, since the `after` parameter wasn't supported on the API side back then. Now that it *is* supported, `oldest_first` can work as expected and doesn't require excessive amounts of memory.
Similar to other endpoints, `before` and `after` are mutually exclusive - `after` is ignored if both are provided, hence the continued need for local filtering.
Notably, using the `after` parameter makes the API return results in ascending order, unlike other endpoints (e.g. the history endpoint, which returns messages in descending order regardless of query parameters).

feat: add `oldest_first` parameter to `Guild.audit_logs`

---

changelog/904.feature.rst
disnake/emoji.py
disnake/enums.py
disnake/guild.py
disnake/integrations.py
disnake/message.py
disnake/role.py
disnake/types/guild.py
disnake/types/integration.py
disnake/types/message.py
disnake/types/role.py
docs/api.rst

https://github.com/discord/discord-api-docs/pull/5724
The new integration type is untested due to region locks (:/), though I don't see why it wouldn't work as the integration structure wasn't changed.

feat: implement role subscription fields

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
changelog/953.misc.rst
changelog/README.rst
noxfile.py
pyproject.toml

Install nox in the virtual environment created by pdm.
This was suggested on Discord around [here](https://canary.discord.com/channels/808030843078836254/913779868985090089/1078451344135954693).

chore(contrib): install nox into the local development environment rather than global

---

disnake/opus.py
pyproject.toml

add some more ruff rules, these pertaining to the pylint plugin. 
Disabled some rules for now that require too much refactoring to add.

refactor(lint): add pylint rules

---

changelog/945.bugfix.rst
disnake/member.py
disnake/raw_models.py
pyproject.toml
tests/test_embeds.py
tests/test_utils.py

https://beta.ruff.rs/docs/rules/#flake8-datetimez-dtz

lint: enable datetime rules

---

changelog/960.bugfix.rst
disnake/channel.py

this would be unset causing an attribute error when trying to access
channel.Flags for DMChannel objects

fix: prevent an attribute error when accessing channel.flags in DMChannels under certain conditions

---

pyproject.toml

This previously worked fine thanks to a transitive dependency through `-Gdocs -> sphinx -> babel>=2.9 -> pytz` :^)
[Babel 2.12](https://github.com/python-babel/babel/releases/tag/v2.12.0) (released a few hours ago) dropped the pytz requirement for py>=3.9 and uses zoneinfo, which means new pyright runs will [fail](https://github.com/DisnakeDev/disnake/actions/runs/4291757014).

fix(typing): install pytz for type-checking examples

---

noxfile.py
pyproject.toml

Everywhere else officially supports python 3.11. We forgot to add python 3.11 as a default for local testing and to black's configuration. CI already includes 3.11 and its required as well.

chore: add py3.11 to local nox testing

---

changelog/967.bugfix.rst
disnake/gateway.py

IP discovery (needed for op 1) previously used 70-byte packets for both sending and receiving, which worked fine up until today. The packets *should* have been 74 bytes, which is the correct and now the only accepted size/structure.
Not sending the correct size results in the connection flow indefinitely stalling on the `sock_recv` here while waiting for a response that never arrives:
https://github.com/DisnakeDev/disnake/blob/6fcc0a6922f1a1612b2f684d977637c5436c837c/disnake/gateway.py#L1028-L1029

fix: use correct packet sizes for voice IP discovery

---

changelog/961.doc.rst
disnake/abc.py
disnake/asset.py
disnake/automod.py
disnake/channel.py
disnake/client.py
disnake/ext/commands/base_core.py
disnake/ext/commands/bot.py
disnake/ext/commands/bot_base.py
disnake/ext/commands/converter.py
disnake/ext/commands/cooldowns.py
disnake/ext/commands/core.py
disnake/ext/commands/interaction_bot_base.py
disnake/ext/commands/params.py
disnake/guild.py
disnake/guild_scheduled_event.py
disnake/i18n.py
disnake/interactions/application_command.py
disnake/iterators.py
disnake/player.py
disnake/reaction.py
disnake/threads.py
disnake/utils.py
disnake/voice_client.py
examples/secret.py
pyproject.toml
test_bot/cogs/injections.py
test_bot/cogs/slash_commands.py
tests/test_utils.py

Enables all relevant `D4*` lint rules, ignoring the ones that aren't usable or only apply to google-style docstrings.
Little to no changes in resulting documentation.

lint: enable more pydocstyle rules

---

changelog/968.misc.rst
pyproject.toml

PyNaCl 1.5 was released last year and shouldn't contain any breaking changes. This was noticed when reviewing #967.
changelog: https://github.com/pyca/pynacl/blob/main/CHANGELOG.rst

chore(deps): allow PyNaCl 1.5 to be used

---

changelog/963.doc.rst
docs/_static/sidebar.js
docs/_static/style.css
docs/_templates/layout.html

Adds some searching of the objects within the sidebar. This should make it easier to find a specific object when you already know a portion of the name.
Thanks to @ItsAleph for the idea and @bast0006 for help with the implementation.
(still has some css stuff to look at but made the pr for the rtd preview)

docs: add searching within sidebar

---

changelog/974.bugfix.rst
disnake/guild.py

`Guild.get_or_fetch_members` uses `Guild.fetch_member` in case `user_ids` contains only 1 unresolved ID. However, it does not cache the value afterwards, which is certainly a bug that we missed.

fix: member not being cached in `Guild.getch_members` in the case of `user_ids` of length one

---

changelog/950.feature.rst
disnake/abc.py
disnake/embeds.py
disnake/enums.py
disnake/ext/commands/bot_base.py
disnake/ext/commands/cog.py
disnake/ext/commands/common_bot_base.py
disnake/ext/commands/converter.py
disnake/ext/commands/core.py
disnake/ext/commands/flag_converter.py
disnake/ext/tasks/__init__.py
disnake/http.py
disnake/iterators.py
disnake/opus.py
disnake/threads.py
disnake/utils.py
pyproject.toml

Enables RSE102, TRY201, and B904 in ruff which correspond to the three errors that flake8-raises provides.

refactor(lint): add flake8-raises

---

.github/workflows/lint-test.yml

This avoids the `pdm export` + `pip install -r` workaround by adding the venv's bin path to `$PATH`.
https://github.com/DisnakeDev/disnake/pull/836#discussion_r1009645787

fix(ci): avoid installing dependencies outside of venv for pyright

---

noxfile.py

Use the native libcst parser. Its not yet compatiable with all 3.10 and 3.11 features (eg match statements and the new union format), but that's okay, as we're compatible with python 3.8 and so we don't use those features.
This should result in codemods being faster both locally and in ci.
~~Depending on when #958 is merged, a change will need to be made to add this environment to both codemods.~~

ci: use the native libcst parser

---

noxfile.py

- Change `codemod` session to always follow up with `autotyping` session (except when listing modules), not just when running non-interactively
- This resolves a somewhat weird issue where where CI would complain about missing codemod changes, but running `nox -s codemod -- run-all` locally didn't change anything
- Set `--hide-progress` if and only if running non-interactively
- lil bit of cleanup/formatting

fix(nox): always run autotyping from codemod session, set `--hide-progress` consistently

---

changelog/741.feature.rst
disnake/guild.py
disnake/types/guild.py

implements and blocked by discord/discord-api-docs#5273

feat: add Guild.max_stage_video_channel_users

---

changelog/986.deprecate.rst
disnake/enums.py
docs/api.rst

https://github.com/discord/discord-api-docs/commit/264938af7399058db863b0a259048e5932cd32e2

chore: deprecate/remove `AutoModTriggerType.harmful_link`

---

changelog/990.misc.rst
disnake/utils.py
tests/test_utils.py

Removes `parse_token`, which has been broken for newer tokens for some time, and was based on unofficial information about the token structure (which, while very unlikely, could technically change).
The "timestamp" part seems to no longer be a timestamp at all, at least there's no discernible pattern; the created datetime thus is completely inaccurate, or results in `ValueError`s if the timestamp exceeds `datetime.MAXYEAR`.
While this function did have a docstring, it wasn't part of the documentation, so I don't think this is worth a breaking changelog entry.

fix!: remove `utils.parse_token`

---

changelog/996.bugfix.rst
changelog/996.misc.rst
disnake/sticker.py
disnake/types/message.py
disnake/types/sticker.py
disnake/types/team.py

Updates some typings in `disnake.types` to match the API docs, which weren't worth a PR on their own.
Almost no runtime changes, except for some new defaults/fallbacks in sticker parsing.

fix(typing): update misc payload types

---

.pre-commit-config.yaml
disnake/ext/commands/context.py
pyproject.toml
tests/test_embeds.py
tests/ui/test_action_row.py

bumps ruff to 0.0.261. Needed before another wave of prs to add more ruff rules.
Changelogs: 
https://github.com/charliermarsh/ruff/releases/tag/v0.0.261
https://github.com/charliermarsh/ruff/releases/tag/v0.0.260
https://github.com/charliermarsh/ruff/releases/tag/v0.0.259
https://github.com/charliermarsh/ruff/releases/tag/v0.0.258

chore(deps): update ruff to 0.0.261

---

changelog/995.bugfix.rst
disnake/audit_logs.py
disnake/types/audit_log.py
docs/api/audit_logs.rst

With the introduction of new automod trigger types for usernames/nicknames, audit log data for automod actions can contain `entry.options.channel_id == null` (or `""`). This PR fixes the resulting deserialization issue.

fix(auditlog): handle `options.channel_id` null value

---

changelog/992.doc.rst
disnake/enums.py
docs/api/events.rst

docs: Clarify docs about the on_member_update event

---

changelog/1033.doc.rst
disnake/message.py
docs/api/channels.rst

Resolves the documentation side of #1033. Voice/Stage channels having a `pins()` method isn't necessarily an issue, especially since the API returns an empty list instead of throwing an error, but this is still something that can be solved by a refactor in the future.

docs: exclude `pins()` from voice/stage channels

---

changelog/1030.bugfix.rst
disnake/automod.py
disnake/guild.py

This improves validation in `Guild.create_automod_rule` and `AutoModRule.edit`, now raising a proper `TypeError` for invalid action types in the most common error cases.
ref: https://canary.discord.com/channels/808030843078836254/1093894067135463475

fix(automod): improve validation for invalid `actions`

---

changelog/1027.bugfix.rst
disnake/state.py
disnake/types/appinfo.py

Trying to access `client.application_flags` when you created a client with `Client(application_id=...)` previously resulted in an `AttributeError`, since the logic was gated by `application_id` not being set in the first place.

fix: always deserialize `application_flags` in ready event

---

docs/version_guarantees.rst
docs/whats_new.rst

added a hyperlink to the release notes on version guarantees 
and a link on the changelog to the version guarantees

docs: add links to version guarantees and whatsnew on both pages

---

changelog/1056.doc.rst
disnake/abc.py

Adds simple documentation note about the new 30d invite link day limit.

docs: add disclaimer about creating >30d invites

---

changelog/1051.bugfix.rst
disnake/abc.py
disnake/member.py
tests/test_abc.py

Fixes a typing issue where `disnake.User` and `disnake.Member` weren't assignable to the `disnake.abc.User` protocol due to mismatching attributes:
ref: https://canary.discord.com/channels/808030843078836254/913779868985090089/1114931830458683422
cc @Enegg

typing: fix `abc.User` protocol structural subtyping

---

disnake/ext/commands/params.py

This is a microoptimization for application command signature parsing, passing down the `inspect.Signature` object through `expand_params` -> `collect_params` -> `isolate_self`, instead of computing a new signature object there.
Also avoids emitting warnings from within string annotations twice, as seen in https://github.com/DisnakeDev/disnake/pull/991#discussion_r1234458388.

fix(params): avoid calling `signature()` twice

---

disnake/member.py

Tiny documentation change to clarify that `Member.current_timeout` also returns `None` when the current timeout value is in the past, allowing users to safely rely on this behavior.

docs: clarify `Member.current_timeout` expiry

---

docs/intro.rst
docs/quickstart.rst

Minimal Bot example does not include the now required Intents definitions.
This PR updates the example to include Intents.default() + message_content so that example will work when copy/pasted by new users.
It also updates the steps to elaborate on the addition of Intents and includes instruction to read "A Primer to Gateway Intents"

add intents definition to minimal bot example

---

scripts/codemods/base.py

followup to #1053, fixes `self.context.module` access in codemods
see https://github.com/DisnakeDev/disnake/actions/runs/5507790654/jobs/10038222160#step:7:97 for previous CI failure

fix(codemod): reinstate context module reference

---

disnake/i18n.py

An invaluable addition when debugging localization problems. No idea why it wasn't done from the beginning.
Also, i don't think a change log entry is required for this change?

chore(i18n): Include failed key in localization warnings

---

changelog/1069.feature.rst
disnake/flags.py
disnake/http.py
disnake/role.py
disnake/types/role.py
docs/api/roles.rst

Adds `RoleFlags` type and `Role.flags`; currently only includes the `in_prompt` flag for onboarding.

feat: role flags

---

changelog/1073.feature.rst
disnake/flags.py
disnake/message.py
disnake/types/message.py
docs/api/messages.rst

Adds `AttachmentFlags` and `Attachment.flags`. Flags `1 << 0` and `1 << 1` also exist, but aren't part of the api docs PR yet.
https://github.com/discord/discord-api-docs/pull/6272/files

feat: attachment flags

---

disnake/message.py
disnake/types/message.py

This doesn't affect 99.9% of cases, but there's no reason to mutate the data here regardless.
https://canary.discord.com/channels/808030843078836254/942319505915412500/1144016456447688835

fix: don't pop key in `MessageReference.with_state`

---

changelog/1087.feature.rst
disnake/activity.py
docs/faq.rst

Bots can now [set a custom status](https://github.com/discord/discord-api-docs/commit/c3935ae1f5fe68228d06d0a9f247e330b1c92dbf) using the `state` field in type 4 activities.
This already works using `activity=CustomActivity(state="Now with 200% more bees!", name="Custom Status")`, but is unnecessarily complicated. `name` is required but not displayed, it just has to be non-empty.
To simplify things, we now just make `state` fall back to `name` if unset, such that `CustomActivity(name="...")` works as-is.

feat(activity): fall back to `name` for custom activities

---

changelog/1096.feature.rst
disnake/audit_logs.py
disnake/types/audit_log.py
docs/api/audit_logs.rst

https://github.com/discord/discord-api-docs/commit/e27f5215c72d779442c6fbd464c979626afcf854
n.b. The field isn't always provided; I've seen it with `guild_subscription` integrations, presumably the same goes for `youtube`/`twitch` integrations

feat(auditlog): support `integration_type` field

---

changelog/1105.doc.rst
disnake/audit_logs.py
docs/api/audit_logs.rst

title should be self-explanatory.
originally brought up in https://canary.discord.com/channels/808030843078836254/1151857056123453441

docs(audit_logs): misc typo/formatting fixes

---

changelog/1095.feature.rst
disnake/automod.py
disnake/integrations.py
disnake/stage_instance.py
disnake/team.py
disnake/threads.py

Noticed that `Team.created_at` didn't exist, and took the opportunity to add it in other places as well - `AutoModRule`, `ForumTag`, `PartialIntegration` (inherently applies to all subclasses), `StageInstance`, and `Team`.

feat: add `created_at` to more models

---

disnake/ext/commands/bot.py
disnake/ext/commands/common_bot_base.py

Removes some duplication related to fetching `owner_id(s)` in `Bot._fill_owners` and `Bot.is_owner`.
Waiting for connect isn't necessary anymore if we do the login first, which puts http into a usable state.

refactor: deduplicate `owner_ids` logic 

---

.github/workflows/lint-test.yml

tiny QoL change to print the git diff in case the libcst CI step changed something
Example:

ci: print libcst diff

---

.pre-commit-config.yaml
disnake/enums.py
disnake/errors.py
disnake/ext/commands/context.py
disnake/ext/commands/help.py
disnake/opus.py
disnake/utils.py
docs/extensions/attributetable.py
pyproject.toml
tests/test_utils.py

It's time for an update, the previously used version has become fairly ancient (relatively speaking, given ruff's quick release cadence). These new versions fix several false positives, and contain a bunch of new rules we might want to enable at some point.

build(deps): update ruff to v0.0.292

---

.github/workflows/lint-test.yml
changelog/1117.misc.rst
noxfile.py
pyproject.toml

Adds 3.12 to the CI version matrix, and updates libcst, pytest, and typing_extensions to the latest versions as they weren't compatible before.
As a temporary workaround, this installs the current aiohttp 3.9.0b0 prerelease, but only in CI; all currently released stable versions don't build on 3.12 yet. 
No code changes specifically for 3.12 in this PR, I'm keeping those separate for another PR.

ci: start testing with python 3.12

---

changelog/1123.bugfix.rst
disnake/threads.py

Fixes #1123.
In the future, we should look into enabling https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch to catch these earlier. Historically those rules have been rather buggy, but they might be more mature now.

fix(threads): move runtime import required for `Thread.permissions_for`

---

changelog/1120.bugfix.rst
disnake/utils.py
tests/test_utils.py

`utils.evaluate_annotation` uses a (per-signature) cache to speed up resolving forwardrefs.
This would previously cache the `eval`'d result *before* continuing to resolve it, meaning subsequent calls with the same stringified annotation return the (incomplete) cached result.
```py
from __future__ import annotations
@bot.command()
async def cachetest(ctx: commands.Context, a: Union['int', 'str'], b: Union['int', 'str']) -> None:
...
#
```
The same thing happens with other unique `evaluate_annotation` behaviors, like turning `UnionType`s into `Union`s.
The correct behavior here is to cache *after* we've done all the remaining steps.

fix(commands): resolve unstringified annotation before caching

---

disnake/ext/commands/common_bot_base.py
docs/extensions/attributetable.py
docs/extensions/builder.py
docs/extensions/exception_hierarchy.py
docs/extensions/fulltoc.py
docs/extensions/nitpick_file_ignorer.py
docs/extensions/redirects.py
docs/extensions/resourcelinks.py
pyproject.toml
tests/ext/commands/test_core.py
tests/helpers.py
tests/ui/test_action_row.py

Enables ruff's `TCH` rules ([flake8-type-checking](https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch)) -- see #1124.
`TCH001`-`TCH003` are left disabled for now, since those are not trivial to take care of in some places. The important one in our case is `TCH004` anyway.
The code changes in this PR are to satisfy the new rules, they weren't actual issues (unlike #1124). As mentioned, `TCH004` isn't perfect and has a couple edge cases, particularly when it comes to submodule imports.

feat(lint): enable ruff `TCH` (flake8-type-checking) rules

---

changelog/1121.feature.rst
disnake/ext/commands/params.py
tests/ext/commands/test_params.py

Changes the lenient `issubclass_` we're using for parts of slash parsing to also support `issubclass_(X[T], X)`, instead of using `issubclass_(get_origin(...), ...)`.
This fixes cases where the interaction annotation is a `Union`, which worked fine before #1037 where I missed this in review.
```py
async def test(inter: Union[disnake.ApplicationCommandInteraction, commands.Context]) -> None:
...
```

fix(commands): handle interactions in union types correctly

---

changelog/1116.misc.rst
disnake/ext/commands/core.py
disnake/ext/commands/params.py
disnake/utils.py
tests/ext/commands/test_params.py

This PR makes slash command signature evaluation use the existing prefix command mechanisms (notably, `utils.evaluate_annotation`), instead of relying on `typing.get_type_hints` which has historically been somewhat [inconsistent](https://docs.python.org/3.11/whatsnew/3.11.html#typing).
There aren't any immediate issues with the previous code; this change is in preparation for Python 3.12 adjustments in the near future. Right now, this *shouldn't* have any effect in practice.
It may look complicated, but it's really just moving around different parts of the code to new locations and dropping `commands.params.signature()` in favour of `utils.get_signature_parameters()`.

refactor: unify slash/prefix command signature evaluation

---

changelog/1111.bugfix.rst
disnake/ui/button.py
disnake/ui/select/channel.py
disnake/ui/select/mentionable.py
disnake/ui/select/role.py
disnake/ui/select/string.py
disnake/ui/select/user.py
docs/api/ui.rst
tests/ui/test_decorators.py

This PR allows the `cls` parameter in select decorators to be provided as a keyword argument again (`@string_select(cls=x, ...)`), whereas it previously had to be specified as positional (`@string_select(x, ...)`).
This regressed in 7467fe83f4bb6ce3fcb8a90b636a13f116ebceb2 and made the `cls` argument not work as expected when provided via keyword.
https://canary.discord.com/channels/808030843078836254/913779868985090089/1149758316126408744 (cc @Enegg)

fix(ui): don't require `cls` argument in select decorators to be positional

---

docs/whats_new.rst

i forgor.
This is a copy of the changelog from stable docs to latest docs - one of the few parts of the release process that aren't automated yet, and probably won't be in the near future.

docs: add v2.9.1 changelog to latest docs

---

changelog/1133.bugfix.rst
disnake/i18n.py
tests/ext/commands/test_base_core.py

Cogs copy all command objects at instantiation (for applying cog-wide parameters), which ends up calling `Option.name_localizations.__eq__` further down the line; at that point, `LocalizationValue`s haven't been linked yet, which results in warnings being thrown incorrectly.
This PR fixes the comparison to bypass the property that's responsible for the warning in this particular case.
(at this point, localization probably deserves a full refactor, but that's a topic for another day)

fix: avoid incorrect warning about broken localizations in cogs

---

changelog/1134.misc.rst
disnake/abc.py
disnake/channel.py
disnake/webhook/async_.py

Bots can now send standard stickers, similar to all normal users. This PR updates the `.send` and `.create_thread` typings accordingly, no runtime change needed.

feat(typing): update send method types to support `StandardSticker`

---

changelog/1085.feature.rst
disnake/webhook/async_.py
disnake/webhook/sync.py

Executing a webhook in a forum channel now supports setting `applied_tags` on thread creation (using `thread_name`).
https://github.com/discord/discord-api-docs/commit/4060a747f67f8a66ff85e1f34c1cc96f0a5a2c23

feat(webhook): add `applied_tags` parameter

---

changelog/1113.feature.rst
disnake/__init__.py
disnake/client.py
disnake/entitlement.py
disnake/enums.py
disnake/flags.py
disnake/http.py
disnake/interactions/base.py
disnake/iterators.py
disnake/sku.py
disnake/state.py
disnake/types/entitlement.py
disnake/types/gateway.py
disnake/types/interactions.py
disnake/types/sku.py
docs/api/entitlements.rst
docs/api/events.rst
docs/api/index.rst
docs/api/interactions.rst
docs/api/skus.rst

https://github.com/discord/discord-api-docs/commit/b97fad33bf2ff7633df32c1a8a206b53aa9fe568 (+ https://github.com/discord/discord-api-docs/commit/b8feadd75e782537545c715fbd71ab4048132363)
~~Since this feature is US-only, I'm unable to test most of it; still working on that part.
Nevertheless, all documented functionality is implemented. The `SKU`/`Entitlement` models have been tested using the example structs provided by the docs, but that's really it.~~  Tested all implemented functionality now.
There are a few `TODO`s scattered across the code regarding testing and naming some things; feedback for those would be appreciated. The api docs are lacking in a few aspects (gateway events, in particular, are somewhat of a guessing game), but most of it is fairly straightforward.

feat: application subscriptions

---

.github/workflows/lint-test.yml
.github/workflows/release.yaml

Followup to #1072.
The `Build + Release` workflow currently runs on all master/version branch commits, skipping all jobs apart from building the package (i.e. the first one).
Since the `Lint + Test` workflow also already goes through the same steps and ensures the package builds correctly, we don't need to do all that twice.

ci: skip unnecessary release workflow run

---

changelog/1151.feature.rst
disnake/client.py

Adds overloads to `Client.[create|edit]_[guild|global]_command()` methods to make typing for them more precise.

refactor(client): Add overloads for application command create and edit methods.

---

changelog/1077.feature.rst
disnake/webhook/async_.py
disnake/webhook/sync.py

Adds a `thread` parameter to `Webhook.fetch_message`, `edit_message`, and `delete_message`, and handles this appropriately in `WebhookMessage.edit`/`.delete`.
Previously, threads were only fully supported in `Webhook.send`.
context: https://canary.discord.com/channels/808030843078836254/942319505915412500/1129444052035698768
https://github.com/discord/discord-api-docs/commit/528975f5c2519c8548eccfe5ee288938382f2141

feat(webhook): improve thread support for webhook messages 

---

changelog/1155.bugfix.rst
disnake/shard.py

The first op we receive when connecting should never be anything other than `HELLO`, but apparently Discord thinks otherwise.
Instead of crashing completely, we now just attempt to perform the requested reconnect.
ref: https://canary.discord.com/channels/808030843078836254/1198023852601659412

fix(shard): handle `RECONNECT` opcode during initial connection flow

---

disnake/user.py

bots can have animated avatars now: https://canary.discord.com/channels/613425648685547541/697138785317814292/1204520610110115852

docs: update supported image formats for bot avatars

---

changelog/1158.doc.rst
disnake/player.py

This PR adds some clarifying documentation around the executable parameters of audio classes based off of internal discussions.

docs: add clarification to executable param

---

README.md

In `README.md` the `you can find more examples in the examples directory`. In PyPi the hyperlink will redirect you to https://pypi.org/project/disnake/examples/ instead of https://github.com/DisnakeDev/disnake/tree/master/examples. This will fix it by adding that url.

fix: Examples Hyperlink Fix

---

changelog/1050.feature.rst
changelog/1162.bugfix.rst
disnake/guild.py

fix(typing): support `Object` category in `create_x_channel`

---

changelog/1164.bugfix.rst
disnake/player.py

`AudioSource.__del__` calls `cleanup()`, which in the case of `FFmpegAudio` can raise an `AttributeError` when spawning the ffmpeg process failed, since `_process` ends up not being initialized yet.
see also https://canary.discord.com/channels/808030843078836254/942319505915412500/1214270424943427615

fix: handle missing `FFmpegAudio._process` in cleanup

---

disnake/interactions/application_command.py
disnake/interactions/message.py
disnake/interactions/modal.py

`entitlements` was only documented on the base `Interaction` type, not any of the subclasses (e.g. `ApplicationCommandInteraction`).

fix(docs): add `entitlements` to interaction subclasses

---

disnake/guild.py

Update the documentation to reflect https://github.com/discord/discord-api-docs/pull/6685
This is a single-word docs-only change, no code has been updated, so testing/etc have been skipped.

docs: update required permissions for prune

---

changelog/1167.misc.rst
disnake/abc.py
disnake/channel.py
disnake/ext/commands/base_core.py
disnake/ext/commands/ctx_menus_core.py
disnake/ext/commands/interaction_bot_base.py
disnake/ext/commands/slash_core.py
disnake/http.py
disnake/message.py

Reduces the amount of unknown types in public-facing APIs. Intended to improve experience with disnake when using pyright in strict mode. I intentionally didn't go too deep and only focused on untyped `*args`/`**kwargs` here since they are (from my experience, at least) one of the most common untyped things when using disnake.

fix(typing): Reduce number of `Unknown`s in public APIs.

---

changelog/1159.bugfix.rst
disnake/gateway.py

see [this thread](https://canary.discord.com/channels/808030843078836254/1209800956741681184)
```
WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.PROTOCOL_ERROR: 1002>, 'Received fragmented control frame'), extra=None)
```
This isn't reproducible[^1], but apparently happened at least once. Blame cloudflare, I guess(?).
[^1]: ...unless you manually feed it one of these weird non-spec-compliant frames: `bot._get_websocket(shard_id=0).socket._reader._protocol.data_received(bytes([0b00001001, 0]))`

fix(gateway): reconnect on protocol errors

---

.github/actions/setup-env/action.yml
.github/workflows/changelog.yaml
.github/workflows/create-release-pr.yaml
.github/workflows/lint-test.yml
.github/workflows/release.yaml
.github/workflows/semantic-pr-title.yml

Updates essentially all github actions to their latest versions, which fixes warnings about the deprecation of the node16 runtime.
See [this](https://github.com/DisnakeDev/disnake/actions/runs/8410062116) old run as an example.
This also migrates from `tibdex/github-app-token` to the official `actions/create-github-app-token` action, which is now recommended in the [docs](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow#authenticating-with-a-github-app) instead.

ci: update actions to avoid node version warnings

---

changelog/1165.feature.rst
disnake/user.py

https://github.com/discord/discord-api-docs/pull/6710

feat: support `banner` parameter in `ClientUser.edit`

---

docs/api/localization.rst

This keeps the attribute names the same as before, but adjusts the descriptions in the docs to match the [reference table](https://discord.com/developers/docs/reference#locales) for consistency, i.e. `en_GB` -> `en-GB`.

chore(docs): adjust locale names in descriptions

---

changelog/1189.bugfix.rst
disnake/asset.py
disnake/sticker.py

https://github.com/discord/discord-api-docs/commit/0a7d731bad7d49c2e49b0687d2a9ec633efeabc9

fix: use media.discordapp.net for gif stickers

---

changelog/1174.feature.rst
disnake/bans.py
disnake/guild.py
disnake/http.py
disnake/types/guild.py
docs/api/guilds.rst

Pretty self-explanatory - adds `Guild.bulk_ban([user1, user2, ...])`, as well as `BulkBanResult` for the API response.
Unlike `Guild.ban`, the default for this is set not to delete any messages. Given that it can be a rather destructive action, I would rather have people be explicit with this.

feat(guild): add `Guild.bulk_ban` method

---

docs/whats_new.rst

as always, copying changelog from stable to latest docs.

docs: add v2.9.2 changelog to latest docs

---

changelog/1197.feature.rst
disnake/enums.py
disnake/message.py
docs/api/messages.rst

implements https://github.com/discord/discord-api-docs/pull/6558
I wasn't able to get a message with type 39

feat(Message): implement new types

---

.github/actions/setup-env/action.yml
noxfile.py
pyproject.toml

Both pdm and twine depend on `importlib-metadata`, but broke due to a change in [importlib-metadata v8.0.0](https://importlib-metadata.readthedocs.io/en/latest/history.html#deprecations-and-removals).
Since updating pdm is rather tricky, we just pin `importlib-metadata<8` there for now:tm:.
In the case of twine, v5.1.1 no longer has this issue (and funnily enough, neither does 5.0.0, but 5.1.0 does).

ci: resolve importlib-metadata errors

---

disnake/channel.py
docs/api/channels.rst
docs/api/guilds.rst

Resolves #1198, by adding a `.. note::` and explicitly documenting the `ThreadWithMessage` namedtuple.

docs(channel): clarify `ForumChannel.create_thread` return type

---

changelog/1180.doc.rst
docs/api/audit_logs.rst

fix: clarify AuditLogAction.overwrite_create

---

disnake/flags.py

`Intents.guild_typing` and `Intents.dm_typing` shouldn't both mention "guild and direct message typing related events".

docs: fix `Intents.*_typing` description

---

changelog/1220.feature.rst
disnake/appinfo.py
disnake/types/appinfo.py

This adds `AppInfo.approximate_guild_count` and `.approximate_user_install_count`, available through `Client.application_info()`.
https://github.com/discord/discord-api-docs/commit/0817246c9f254a4c2537146b49b8758048abdd70
https://github.com/discord/discord-api-docs/commit/9c45aa73fb353cba97e71257a8e5374ba53876f7

feat(app): add guild/user install count fields

---

disnake/ext/commands/cog.py

Basically the check methods on `commands.Cog` were documented to be either a normal function or a Coroutine, though this wasn't reflexed on the typing part. This PR fixes that issue, refer to the attached image for clarifications.

fix(cog): fix typing of cog check methods 

---

changelog/1233.feature.rst
disnake/abc.py
disnake/channel.py
disnake/ext/commands/context.py
disnake/interactions/application_command.py
disnake/interactions/base.py
disnake/interactions/message.py
disnake/interactions/modal.py
disnake/message.py
disnake/state.py
disnake/ui/select/channel.py
tests/interactions/test_base.py

Followup to #1012 - `interaction.channel` and other channel fields (slash params, channel select menus, ...) in interactions are now proper `DMChannel`/`GroupChannel` objects in dms/gdms respectively, instead of `PartialMessageable`. They don't have recipient data, since the API doesn't provide the field in interactions.
The core addition is this, everything else is primarily documentation/typing adjustments: https://github.com/DisnakeDev/disnake/blob/dfaadc6708f756b44955d2be55a2942e449de6f4/disnake/state.py#L2074-L2079

feat: deserialize dm/group channels in interactions

---

changelog/1241.bugfix.rst
disnake/gateway.py

This should hopefully fix a spurious websocket quirk introduced in aiohttp 3.9.0, which results in shards fully reconnecting instead of resuming on abrupt connection loss. See https://github.com/aio-libs/aiohttp/issues/8138 and the comment left in the code for more details.
There are several different workarounds for this, this is one of them. It's not pretty, but likely the most reliable one, besides another one I experimented with a while ago which relied on aiohttp internals too much :/
Only cpython 3.10 and earlier is affected, since 3.11.0a6+ uses uvloop's ssl implementation, which doesn't have this particular issue with ssl transport lifecycles.
Some references:
- https://canary.discord.com/channels/808030843078836254/1196843077659283496
- …

fix: attempt resume on websocket closure with `close_code = 1000` in edge cases

---

disnake/client.py

The class method run() for the class disnake.ext.commands.Bot did not have any information on what parameters it has. This is a quite small change but quite important as nearly all disnake bots use this method to start the bot. If people don't read the docs or simply just are new, they might not know what to pass.

docs: Add parameter info to disnake.ext.commands.Bot.run() docstring

---

changelog/1247.feature.rst
disnake/guild.py
disnake/http.py

feat(guild): implement new fetch role endpoint

---

.pre-commit-config.yaml
disnake/app_commands.py
disnake/ext/commands/converter.py
disnake/ext/commands/params.py
disnake/ext/tasks/__init__.py
disnake/interactions/base.py
disnake/state.py
disnake/utils.py
pyproject.toml
tests/ext/commands/test_params.py

Updates ruff from v0.3.4 to v0.8.0.
There are essentially no runtime changes, other than some comparisons now using `is` instead of `==` where applicable, and two `raise`s that have somehow been missing for a while (on a code path that should never be hit in the first place, but still).
The main changes are from these two rules:
- https://docs.astral.sh/ruff/rules/parenthesize-chained-operators/ (`RUF021`)
- https://docs.astral.sh/ruff/rules/type-comparison/ (`E721`)

build(deps): update ruff to v0.8.0

---

changelog/1245.feature.rst
disnake/flags.py

feat(flags): implement new member flags

---

changelog/1252.bugfix.rst
disnake/ext/commands/ctx_menus_core.py
tests/ext/commands/test_base_core.py

The sanity check for cases where both `@command(default_member_permissions=)` and `@default_member_permissions()` are used on the same callback was adjusted in #678.
Putting the `@default_member_permissions()` decorator *below* the application command decorator while also using `Cog(..., *_command_attrs=...)` (see example below) isn't supposed to throw an exception, and while this holds for `@slash_command` and `@message_command`, it didn't work with `@user_command`.
This makes all decorators work the same way.
```py
class Misc(
commands.Cog,
user_command_attrs={"default_member_permissions": disnake.Permissions(32)},
):
@commands.user_command()
@commands.default_member_permissions(64)
async def test(self, inter) -> None:
await inter.send("pong!")
```

fix: remove decorator check in `InvokableUserCommand`

---

.github/workflows/lint-test.yml

This is a bandaid fix for a PDM bug in Python 3.12.8, which GitHub actions runners started using yesterday.
It's fixed in the latest PDM release, but we're rather far behind already, and don't have the capacity to upgrade PDM currently. This just gets CI to run again for now.

fix(ci): pin Python 3.12 in matrix to 3.12.7 due to PDM bug

---

changelog/1256.feature.rst
disnake/channel.py
disnake/message.py

Now that `Message.channel` can potentially be a `GroupChannel` (in user app interactions, see #1233), having `get_partial_message` available on all but one of the possible types is annoying.
This fixes that, adding `get_partial_message` to the common interface that all messageable channel types support, even if partial messages in this context may not be incredibly useful.

feat(channel): add `GroupChannel.get_partial_message`

---

changelog/1267.bugfix.rst
disnake/message.py
disnake/state.py

Rebinding guild/member references on shard reconnect also updates `Message.interaction.user`; `interaction` is deprecated, so this should use the underlying `_interaction` instead to avoid copious amounts of `DeprecationWarning`s (one per cached message).

fix(state): prevent `DeprecationWarning` on shard reconnect

---

changelog/1285.bugfix.rst
disnake/ext/commands/slash_core.py

While the docstring of subcommand groups is largely useless (as descriptions of subcommand groups are not exposed in the UI anywhere), it should still be parsed to retrieve [localization key](https://docs.disnake.dev/en/stable/ext/commands/slash_commands.html#localizations) for the group name, if any.
see also: https://canary.discord.com/channels/808030843078836254/1337797831347671122

fix(commands): retrieve localization key for subcommand groups from docstring

---

changelog/1290.bugfix.rst
disnake/ext/tasks/__init__.py

fix(tasks): support `change_interval` before first loop run

---

changelog/1287.bugfix.rst
disnake/abc.py
disnake/channel.py
disnake/threads.py

This avoids errors related to `Object` guilds on guild-dependent channel properties when used with user apps. Stubbing methods isn't ideal, but it's arguably better than throwing `AttributeError`s at random.
Closely related to #1236, the future of which is still very much undecided at this point.
(context: since interactions don't receive a (proper) guild object, we generally substitute it for `Object` if necessary. This works fine:tm: for the most part, but some properties (rightfully) expect an actual `Guild` object)

fix(channel): improve handling of placeholder guilds in `GuildChannel` and `Thread`

---

changelog/1324.bugfix.rst
disnake/http.py

Surfaced from migrating to uv, and seeing that our dependencies are, as a reminder, not bound to what is supported on python 3.8.
tested with the latest aiohttp version and had some deprecated warnings.
Have not tested.

fix: use ClientWSTimeout for timeout to WS

---

disnake/app_commands.py

fixes #1338. There's no difference in practice, it's just an unusual pattern.

fix: change `Option.from_dict` to return cls instance instead of specifically `Option`

---

pyproject.toml
scripts/codemods/typed_permissions.py

At some point this was disabled/never enabled, but it should be. 
Required by #1341, if we want to run pyright on scripts.

fix(dev): enable typechecking on scripts

---

.github/workflows/lint-test.yml

While working on #1322, I was in desperate need of being able to see some artifacts that our ci does not currently have great logging, this has libcst provide the diff as a job summary as well as in-line in the logs. 
see https://github.com/DisnakeDev/disnake/actions/runs/17488021841?pr=1336 for an example.

feat(ci): add libcst diff as a check summary to GH actions

---

.github/workflows/lint-test.yml

fix(ci): stop vscode from complaining about invalid syntax

---

.github/workflows/lint-test.yml

In the event that lint fails the rest of ci does not need to run, as we are spending minutes on something that will be pushed away, and will need to re-run. the linting in also quickly completes, meaning this won't be delaying our other jobs more than a couple seconds (and not at all if pdm isn't cached).

fix(ci): require lint for all jobs

---

.pre-commit-config.yaml
pyproject.toml

Working on the pre-commit part of CI and saw a deprecation warning from pre-commit. Bumping the hooks to solve that, and sneaking in a ruff bump.

fix: bump versions of hooks for pre-commit

---

changelog/1350.bugfix.rst
disnake/member.py
disnake/types/user.py
disnake/user.py

This fixes a couple minor issues with `user_update`/`member_update` events not triggering correctly for some field changes, namely:
- The old `Member` in `member_update` now has the correct `avatar_decoration` set.
- A `user_update` now triggers for updates to `collectibles`, and the old `User` now has `collectibles`, `primary_guild` and `system` set.

fix(gateway): fix missing `user_update` event for new attributes, missing attributes in `member_update` event

---

changelog/1356.misc.rst
pyproject.toml
setup.py

Previously, new modules or files would need to be explicitly added to setup.py
This moves the configuration to pyproject.toml and drops the requirement they must be explicit. At this point, this means the *only* reason for setup.py is our custom version indicators.

feat(packaging): migrate packages out of setup.py

---

.github/actions/setup-env/action.yml
.github/workflows/lint-test.yml
noxfile.py
pyproject.toml

solves an issue blocking us from upgrading to sphinx 8.4, which is that if docs can't be installed on all supported python versions, typechecking won't pass.
This moves every nox dependency definition into an ExecutionGroup list which stores the dependencies for a specific session and environment. These dependencies are subsequently installed in CI. 
This groups allow pyright and typechecking to be ran on specific segements of our repository, documentation for example will only be typechecked with pyright 3.8.

ci: run ci with specific environment definitions

---

pyproject.toml

these rules got disabled accidently in 5b43b21f6bbf4751489f39489fdffaaf11e4c762
and shouldn't have been

fix: re-enable other TC rules

---

.github/dependabot.yaml

in correlation with #1402, adds dependabot configuration to bump actions automatically

ci: add dependabot to update github actions

---

changelog/1414.feature.rst
disnake/message.py
disnake/types/message.py
docs/api/messages.rst

https://discord.com/developers/docs/resources/message#message-call-object
Didn't add an edit handler but also doesn't even look like that matters? To my knowledge, these messages shouldn't be received over the gateway for bots anyways.

feat: add support for message call objects

---

.github/dependabot.yaml

Noticed in #1415 that Dependabot doesn't seem to run on.github/actions without this specific piece of code. The `*` is important to the directory. 
Tested locally with the dependabot's cli

fix: run dependabot on reusuable workflows
