.flake8, discord/channel.py, discord/client.py, discord/enums.py, discord/guild.py, discord/http.py, discord/party.py
I have added everything again which were in #1 (hopefully), but I will be needing a review on the Party feature…
Custom features
=> I think I have added all those features again

disnake/channel.py, disnake/ext/commands/bot.py, disnake/guild.py, disnake/party.py, docs/api.rst
docs for Party class and typos (tested and working perfectly)
- [x ] If code changes were made then they have been tested.
- [x ] I have updated the documentation to reflect the changes.
- [x ] This PR fixes an issue.
- [ x] This PR is **not** a code change (e.g. documentation, README, ...)
=> Fixed some typos and added docs for Party class

disnake/colour.py
=> Added an alias for og blurple

setup.py
=> add aiohttp's [speedups] to [speed]

README.rst
=> fix missing(?) newline in readme

disnake/ext/commands/bot.py
=> Fix the watchdog being on by default.

examples/user_echo_webhook.py
This is a script wherein the user can input a UserID as well as message content, and the bot will create a webhook to "impersonate" specified user, so to speak.
=> Created new example - user_echo_webhook.py

examples/user_echo_webhook.py
Made changes to examples/user_echo_webhook.py
=> Fixing my broken example.

disnake/ext/commands/bot.py
Ew what the hell was I thinking before
- [xx] If code changes were made then they have been tested.
=> Clean up watchdog a bit to not be hacky

disnake/asset.py, disnake/role.py, disnake/types/role.py
=> Implement role icons

disnake/ext/commands/params.py, disnake/ext/commands/slash_core.py, disnake/utils.py
Please add actual parsing code thanks
=> Create a param parsing template

examples/slash_commands/old.py
=> broken example

disnake/ext/commands/params.py
=> overload typehinting

disnake/ext/commands/params.py, disnake/ext/commands/slash_core.py, disnake/interactions/application_command.py, disnake/interactions/base.py
We'll have to do a fair bit of cleaning up later.
=> Implement autocomplete for Param

examples/slash_commands/param.py
=> Add an autocomplete example

disnake/ext/commands/params.py
A lot of people incorrectly use Param as an annotation instead of a default.
```py
async def faulty(inter, option: Param(1, desc="hello")):
...
```
```
Traceback (most recent call last):
File "C:\Users\D\code\thesadru\disnake\test.py", line 11, in <module>
async def faulty(inter, option: Param(1, desc="hello")):
File "C:\Users\D\code\thesadru\disnake\disnake\ext\commands\bot.py", line 463, in decorator
result = slash_command(
File "C:\Users\D\code\thesadru\disnake\disnake\ext\commands\slash_core.py", line 463, in decorator
return InvokableSlashCommand(
File "C:\Users\D\code\thesadru\disnake\disnake\ext\commands\slash_core.py", line 191, in __init__
params = extract_params(func, self.cog, docstring['params'])
File …
```
=> Add a more helpful error

disnake/abc.py, disnake/enums.py
=> PartyType enum

disnake/errors.py, disnake/ext/commands/params.py, disnake/interactions/base.py, examples/slash_commands/param.py
We should've had this for a long time already
=> Improve unknown interaction errors

disnake/app_commands.py, disnake/ext/commands/base_core.py, disnake/ext/commands/bot.py, disnake/ext/commands/ctx_menus_core.py, disnake/ext/commands/params.py, disnake/ext/commands/slash_core.py, disnake/interactions/application_command.py, examples/slash_commands/param.py
Converters now support enums. Integer enums were fixed.
New guild_only attribute
Interactions are now annotated as covariant to allow for subclasses
=> Fixed enumeration with param

disnake/ext/commands/context.py
=> "HelpCommand" is not accessed

disnake/enums.py
=> Add 'PartyType' to __all__ tuple

disnake/ext/commands/slash_core.py, disnake/player.py
Add ValueError("FFmpegAudio cannot be read more than once")
=> Add ValueError

.github/workflows/lint.yml
Without this hook, pull requests from forked repositories won't have the
lint action as part of the PR.
=> Run lint action on pull requests

examples/slash_commands/param.py
This code isn't tested but I think it works.
=> Add @slash_command.autocomplete() example.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md, .readthedocs.yml, examples/converters.py
This updates the issue/PR templates as well as the contributing guide, and replaces legacy options used in `.readthedocs.yml`.
=> Update issue/PR templates

README.ja.rst, README.rst, disnake/http.py, docs/_templates/layout.html, docs/conf.py, docs/faq.rst, docs/locale/ja/LC_MESSAGES/faq.po, setup.py
=> Change github.com/EQUENOS to github.com/DisnakeDev

disnake/interactions/base.py
This pull request fixes possibly misunderstand in `original_message` documentation.
I will create this PR as draft since I would like someone to review it. (My English isn't the best)
Linked issue: #61
=> Fixed possibly misunderstand in `Interaction.original_message` documentation.

disnake/enums.py
=> Fixed wrong PartyType.checkers ID.

disnake/guild.py, disnake/http.py, disnake/types/guild.py
approximate_member_count and approximate_presence_count, is now added.
This should be better than the last one, and it works with black, I ran black . in the base folder what is now, will work with black.
All good :D
=> Add approximate member/presence count to guilds

docs/api.rst
Fix #168 
If I missed any derived classes let me know.
Preview: https://pr-170-preview.readthedocs.io/en/latest/api.html
=> fix interactions inherited members

disnake/enums.py
That embedded activity doesn't work anymore.
=> Deleted invalid PartyType ID.

disnake/webhook/async_.py
This fixes an issue someone had in the Discord server. I basically copied what `_edit_handler` does.
=> Fix images not showing in embed when using `Interaction.edit_original_message`.

README.md
fix disnake banner does not display banner in PyPI.
=> fix disnake banner does not display banner in PyPI

examples/views/button/paginator.py
See https://canary.discord.com/channels/808030843078836254/883342278280745030/921092266788020324.
=> Updated `paginator.py`.

disnake/message.py
=> Add `fail_if_not_exists` to `Message.reply()`

disnake/ext/commands/params.py, disnake/interactions/application_command.py, disnake/invite.py, disnake/message.py, docs/api.rst
[see title]
Just a few things I noticed while writing the changelog
=> Fix a few issues in the docs of new features

disnake/guild.py, disnake/guild_scheduled_event.py, disnake/http.py
Closes [this card](https://github.com/DisnakeDev/disnake/projects/1#card-75001340).
=> Add support for reason in scheduled events.

disnake/role.py
(see title)
<sup>Before.</sup>
<sup>After. Slash commands mentions are broken btw.</sup>
=> fix(Role): Double @ when mentioning the default role.

disnake/ext/commands/common_bot_base.py, disnake/utils.py, docs/api.rst
Add a method that loads all extensions in a directory.
=> Implement load_extensions

disnake/app_commands.py, disnake/ext/commands/params.py, disnake/ext/commands/slash_core.py, disnake/http.py, disnake/interactions/base.py, disnake/types/interactions.py, disnake/utils.py
small typing improvements, cherrypicked from a wip branch
=> Improve typing of autocomplete/choices and docstring parser

examples/views/button/row_buttons.py
I often look at an example. And I noticed that the class is called row_button and decided to rename it.  https://www.python.org/dev/peps/pep-0008/#class-names
=> CamelCase style

disnake/__init__.py, disnake/ext/commands/__init__.py, disnake/types/__init__.py, disnake/ui/__init__.py, disnake/webhook/__init__.py
=> chore: add disnake development to licensing in all */__init__.py

README.md
=> fix: use new guide link as the guide was restructured

examples/views/button/paginator.py, examples/views/disable_view.py
Add a _quit_ button in `paginator.py`. Fix issue in `disable_view.py`
=> Patch up some examples with views

disnake/guild_scheduled_event.py, disnake/http.py
=> Fix `GuildScheduledEvent.fetch_users`

disnake/embeds.py
=> feat: add embed default color attribute

disnake/ext/commands/params.py
=> fix: `Union` in slash commands raising an error

disnake/threads.py, disnake/types/threads.py
implements https://github.com/discord/discord-api-docs/commit/53ee0109b874bde5ec2316379bf266bb332630a0
=> feat: add thread create_timestamp

disnake/message.py, disnake/state.py, disnake/types/message.py
closes #290
Implements disnake.Message.thread which is the thread created on the message.
=> feat(Message): add thread property

disnake/permissions.py
Refactor permission generation. The existing way of 0b integers is prone to breaking and is hard to read.
Additionally, adds a missing events classmethod.
=> refactor Permission classmethods

disnake/enums.py, docs/api.rst
Added the new Sketch Heads (supposedly replacement of Doodle Crew, but it still works) and Ocho (Publicly announced) activities.
=> feat(PartyType): add sketch_heads and ocho activities

disnake/invite.py
I'm not sure if this value ever existed, but it was documented in [this commit](https://github.com/discord/discord-api-docs/commit/43f6597edb2a5748a18507de0a17c1039bec4db1) and removed in [this PR](https://github.com/discord/discord-api-docs/pull/1115).
Fetching a revoked/deleted invite raises `NotFound` error: `404 Not Found (error code: 10006): Unknown Invite`, so this value is really unnecessary.
Also, I'm not sure if just remove this property, but it might be breaking (even though it's always ``None`` ), any suggestions are always appreciated.
=> docs(Invite): deprecate revoked

disnake/guild.py, disnake/types/sticker.py
I wasted 2 hours trying to figure out why it wasn't working and it was because of that, not sure if it's me or ddocs are just confusing there. 😔
=> fix: error when creating a sticker

disnake/__init__.py, disnake/ext/commands/cooldowns.py, disnake/ext/commands/ctx_menus_core.py, disnake/ext/commands/interaction_bot_base.py, disnake/ext/commands/slash_core.py, disnake/guild.py, disnake/interactions/application_command.py, disnake/types/sticker.py, docs/whats_new.rst, examples/views/button/paginator.py
Merging stable back into master for version bump and changelog :)
<sup>wow what a great title</sup>
=> v2.3.1 stable merge

disnake/guild.py
This method is a bulk get-or-fetch method. A detailed description can be found in the docstring.
=> feat(Guild): add get_or_fetch_members

disnake/__init__.py
updates current version indicator to 2.5.0 for development
=> chore: update version indicator to 2.5.0 alpha

disnake/__init__.py, disnake/client.py, disnake/emoji.py, disnake/guild_preview.py, disnake/http.py, disnake/types/guild.py, docs/api.rst
Add GuildPreview, which allows viewing a preview Guild for any discoverable guild.
=> feat: add GuildPreview

disnake/guild.py
Add a return type in doc in `disnake.Guild.create_template`
=> update doc of `disnake.Guild.create_template`

disnake/client.py
Simple isinstance to check token's type to make error messages slightly less cryptic, [yw arl](https://discord.com/channels/808030843078836254/925508492574474270/946347861820440576).
=> Ensure token is of type str

.pre-commit-config.yaml, disnake/backoff.py, disnake/flags.py, disnake/utils.py, requirements_dev.txt, test_bot/cogs/injections.py
Updates pre-commit, taskipy and black to the latest version and formats the code according to the latest changes in black.
This should be merged together with #311 as both change workflows, which affects other PRs.
=> chore: update dev dependencies

disnake/ext/commands/converter.py, disnake/ext/commands/errors.py, docs/ext/commands/api.rst, docs/ext/commands/commands.rst
This PR adds `GuildScheduledEventConverter` and a `GuildScheduledEventNotFound` exception.
It also updates the order of classes in `__all__` and in the docs to improve maintainability, and adds previously missing docs for new converters and `ObjectNotFound` (which I noticed while reording stuff) (yay scope creep).
fixes #367
=> feat: add scheduled event converter

disnake/interactions/application_command.py, docs/api.rst
This PR adds `GuildCommandInteraction`, `UserCommandInteraction` and `MessageCommandInteraction` to the docs, and updates the `VoiceRegion` docs to match the recent changes.
=> docs: add interaction annotation types, update voice regions

disnake/channel.py, disnake/message.py, disnake/state.py, disnake/webhook/async_.py, disnake/webhook/sync.py
see title
no public interface changes, just a small internal improvement to avoid possible future mishaps
=> refactor: improve `_WebookState` typing

disnake/http.py
=> fix: role icon/emoji editing

disnake/interactions/base.py, disnake/interactions/modal.py
=> docs: add missing version directives to new modal changes

disnake/gateway.py
fixes #314, see that issue for more details
This has been in testing for a while and (as expected) hasn't resulted in any issues.
=> fix: remove unnecessary gateway ratelimit reset

disnake/state.py
A channel's associated scheduled events should also be deleted when that channel is deleted, as Discord doesn't emit separate `guild_scheduled_event_delete` events in that case.
ref: https://github.com/discord/discord-api-docs/issues/4581#issuecomment-1053760414
=> fix: delete scheduled events on channel delete

disnake/invite.py
=> feat: add boost count to invite guilds

disnake/ext/commands/common_bot_base.py
=> fix: console spam when using reload

docs/api.rst
https://discord.com/channels/808030843078836254/883342278280745030/960563200800223286
regression from #363
=> docs(modals): fix missing inherited members of `ModalInteraction`

.pre-commit-config.yaml
Fixes import errors in CI by updating black to `22.3.0`, see https://github.com/psf/black/issues/2964.
=> ci: update pre-commit hooks

examples/low_level_components.py
Since we have no examples on directly sending components and using listeners for them, I thought it'd be nice to add an example to the list before I go on exam microhiatus.
It's probably a tad too wordy so any feedback is welcome.
=> feat: Add simple low-level component example

disnake/guild.py, disnake/invite.py, disnake/threads.py
remove features marked as deprecated from version 2.4
=> chore: remove deprecated features since version 2.4

disnake/interactions/application_command.py, disnake/interactions/message.py, disnake/interactions/modal.py
add repr methods to interaction data classes
=> feat: add repr methods to interaction data classes

disnake/interactions/base.py
This wasn't implemented while the api didn't support it-- but now it does!
=> feat: support embed images in interaction edit_message

disnake/channel.py, disnake/state.py, disnake/threads.py, disnake/types/channel.py, disnake/types/raw_models.py, disnake/types/threads.py
=> feat: add support for `last_pin_timestamp`

disnake/guild.py
this is not required by the api to create a stage channel
=> feat: provide a default argument for topic when creating a stage channel 

disnake/channel.py, disnake/permissions.py
this seems to have been concretely decided. (it was not when we merged the original forum channel)
=> feat: add create_forum_posts permission alias

disnake/__init__.py, disnake/audit_logs.py, disnake/channel.py, disnake/client.py, disnake/enums.py, disnake/guild.py, disnake/template.py, disnake/voice_region.py, docs/api.rst
removes the disnake.VoiceRegion enum and replaces it with a custom class
=> feat!: Voice region strings and VoiceRegion data class

disnake/raw_models.py, disnake/state.py, disnake/types/raw_models.py, docs/api.rst
add raw_thread_delete, raw_thread_update, and raw_thread_member_remove events
=> feat: add raw_thread_delete, raw_thread_update, and raw_thread_member_remove events

disnake/channel.py, disnake/http.py, disnake/types/threads.py
https://github.com/discord/discord-api-docs/pull/4850
~~PR 2.0 coming soon!!1! this is 1.5~~
=> feat(ForumChannel): return message when creating thread

disnake/abc.py, disnake/app_commands.py, disnake/ext/commands/base_core.py, disnake/ui/item.py
missing from when these classes were implemented.
=> docs: mark what classes implement Command abcs

docs/api.rst
=> docs: update `on_member_update` to be inclusive of future changes

disnake/message.py
adds Message.application_id as documented [here](https://discord.com/developers/docs/resources/channel#message-object-message-structure)
=> feat: add disnake.Message.application_id

disnake/audit_logs.py, disnake/ext/commands/bot_base.py, disnake/ext/commands/converter.py, disnake/ext/commands/core.py, disnake/ext/commands/ctx_menus_core.py, disnake/ext/commands/params.py, disnake/gateway.py, disnake/member.py, docs/conf.py, requirements_dev.txt
- updated to pyright 1.1.244
- removed some `# type: ignore`s
- added some new `# type: ignore`s :)
- added generic parameters to message/user application command definitions, avoiding some `Unknown`s
- added `event` to default dispatch callback
- changed `roles` parameter of `Member.edit` to `Sequence`, as `List` is invariant
=> typing: update pyright, fix new issues

docs/whats_new.rst
=> docs: add v2.5.1 changelog

disnake/ext/commands/core.py, disnake/state.py
- add support for voice channels to commands.is_nsfw
- dispatch on_reaction_add/remove for reactions in Threads
=> fix commands.is_nsfw and reaction_remove for voice channels and threads

disnake/audit_logs.py, disnake/types/webhook.py, disnake/webhook/async_.py, disnake/webhook/sync.py, docs/api.rst
=> feat: add `Webhook.application_id`

.readthedocs.yml
It adds the ability to download the documentation for offline use.
~-  If code changes were made, then they have been tested~
~-  I have updated the documentation to reflect the changes~
~-  I have formatted the code properly by running `task lint`~
~-  I have type-checked the code by running `task pyright`~
~-  This PR fixes an issue~
~-  This PR adds something new (e.g. new method or parameters)~
~-  This PR is a breaking change (e.g. methods or parameters removed/renamed)~
=> Add Generation for Documentation Download

disnake/activity.py, disnake/channel.py, disnake/raw_models.py, disnake/threads.py, docs/api.rst
=> typing: more explict "type" typings

disnake/abc.py, disnake/channel.py, disnake/flags.py, disnake/threads.py, disnake/types/channel.py
adds channel flags to all currently supported channels.
=> feat: add channel flags to all channels

CONTRIBUTING.md
Moves the contributing guidelines to the repository root (see [docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)) to improve visibility, and adds a link to the [discussions](https://github.com/DisnakeDev/disnake/discussions) section of the repo.
=> docs: update `CONTRIBUTING.md` and move to repository root

.github/workflows/lint-test.yml, noxfile.py
=> ci: run docs creation in workflows

examples/background_task.py, examples/basic_bot.py, examples/basic_voice.py, examples/converters.py, examples/slash_commands/subcmd.py, examples/user_echo_webhook.py, examples/views/select/dropdown.py, pyproject.toml
Adds the `examples/` directory to the pyright includes, and fixes several minor pyright errors in the examples that appeared as a result.
depends on #563
=> typing: run pyright on examples

README.md, docs/index.rst
This pull request just updates the README.md file a bit.
- Added hyphens in words where it's needed
- Updated the PyPI URL, as the domain had changed a few months ago
=> docs: update the PyPI URL & minor wording

disnake/channel.py, disnake/types/channel.py
=> fix: assume None is an empty channel name for guild channels

disnake/guild.py
=> feat: add bitrate param in create_stage_channel

disnake/guild.py, disnake/http.py, disnake/types/guild.py
see https://github.com/discord/discord-api-docs/commit/a54996ba563e88eebf213c96fbb3089bf3cdc7ae
=> feat: add `Guild.edit_mfa_level`

disnake/interactions/application_command.py
Adds guild_id and member typings to GuildCommandInteraction
=> chore: add more typings to GuildCommandInteraction

disnake/guild.py
=> feat: add `slowmode_delay` parameter to `create_voice_channel`

disnake/types/interactions.py
Slightly reworks interaction typing by properly separating them based on type, and adds missing types 4 and 5 to `InteractionType`. No real improvement here yet, but other changes will build on top of this.
Core changes are the addition of `PingInteraction` and the use of more specific type literals in the different interactions.
=> typing: improve interaction typings

disnake/interactions/base.py, disnake/types/interactions.py
implements https://github.com/discord/discord-api-docs/commit/f4e3955f673c7f26b665f64411d8353bda7d0525 (https://github.com/discord/discord-api-docs/pull/5131)
=> feat: add Interaction.app_permissions

disnake/components.py, disnake/interactions/modal.py, disnake/ui/action_row.py, examples/modal.py, tests/ui/test_action_row.py
adds selects to modals and modal interactions. 
When I made this, I think I was forgetting something, but I can't remember what it was...
=> feat: support selects in modals

.github/workflows/check-pull-labels.yaml
adds a CI workflow for checking that a DO NOT MERGE label is not present
=> ci: add a workflow checking for a "do not merge" label and block the merge if it exists.

disnake/channel.py, disnake/client.py, disnake/ext/commands/cog.py, disnake/ext/commands/flags.py, disnake/ext/tasks/__init__.py, disnake/guild.py, disnake/member.py, disnake/utils.py, requirements/requirements_dev.txt, tests/test_utils.py
adds [flake8-comprehensions](https://pypi.org/project/flake8-comprehensions) for checking for inefficient comprehensions and suggesting a better solution.
=> chore(lint): add flake8-comprehensions for catching comprehension mistakes

.flake8, disnake/abc.py, disnake/audit_logs.py, disnake/client.py, disnake/ext/commands/base_core.py, disnake/ext/commands/bot_base.py, disnake/ext/commands/cog.py, disnake/ext/commands/common_bot_base.py, disnake/ext/commands/converter.py, disnake/ext/commands/core.py, disnake/ext/commands/ctx_menus_core.py, disnake/ext/commands/errors.py, disnake/ext/commands/interaction_bot_base.py, disnake/ext/commands/slash_core.py, disnake/guild.py, disnake/interactions/__init__.py, disnake/invite.py, disnake/iterators.py, disnake/shard.py, disnake/state.py, disnake/ui/button.py, disnake/ui/item.py, disnake/ui/select.py, disnake/utils.py, disnake/voice_client.py, disnake/webhook/__init__.py
Solves some flake8 errors previously not solved.
=> chore(lint): resolve some ignored flake8 errors

changelog/630.feature.rst, disnake/enums.py, docs/api.rst
=> feat: add cancelled spelling to alias `GuildScheduledEventStatus.canceled`

changelog/660.misc.rst, disnake/flags.py, disnake/permissions.py, tests/test_flags.py
[https://docs.python.org/3/reference/datamodel.html#object.\_\_init_subclass\_\_](https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__) :)
=> refactor: remove fill_with_flags

changelog/710.doc.rst, disnake/client.py, disnake/guild.py
=> docs: improve documentation of `strict` kwarg on getch methods

docs/ext/commands/slash_commands.rst, docs/whats_new.rst
=> docs: fix link to parameter injections example

changelog/522.doc.rst, changelog/565.doc.rst
=> docs: unify #522 and #565 changelog entries

changelog/733.feature.rst, disnake/ui/view.py
simply returns the view instance from add_item, remove_item, clear_items.
supersedes and closes #258
=> feat: view method chaining

changelog/743.bugfix.rst, disnake/member.py
discord api docs: https://github.com/discord/discord-api-docs/commit/e3921e168aa167503ae193439abe70106b58d914
=> don't use deprecated @! mention syntax

disnake/guild.py
https://github.com/discord/discord-api-docs/commit/969ccfe568b7a9ab68a0dc5991e9183c871da376
=> docs: add the valid options for afk_timeout

disnake/errors.py, disnake/interactions/base.py
Fixes a couple broken `versionadded`/`versionchanged` directives.
=> docs: fix version directives

docs/_static/disnake.svg
make the svg valid again after messing it up by including a comment in an xml file in #756
=> fix: make svg valid again

disnake/ext/commands/params.py
=> fix: handle edge case with `Optional[Literal[...]]` parameter annotations

disnake/__init__.py, docs/whats_new.rst
changelog and version bump for v2.5.3
=> release: v2.5.3

docs/whats_new.rst
ported from #773 to main branch
=> docs: add v2.5.3 changelog

disnake/mentions.py
=> fix(docs): fix spelling

changelog/_template.rst.jinja, docs/conf.py, pyproject.toml, requirements/requirements_docs.txt, requirements/requirements_tools.txt
=> deps(docs): update towncrier to v22.8.0

disnake/automod.py, disnake/guild.py
Adds metadata limits like maximum number of keywords in a rule, and fixes other minor documentation mistakes.
=> docs(automod): misc content fixes

requirements/requirements_dev.txt
=> deps: update testing dependencies

disnake/client.py
=> docs: remove parameters that were documented on the wrong class

changelog/791.feature.rst, changelog/791.misc.rst, disnake/__main__.py
fixes a few bugs with the cli and adds some other enhancements
=> feat(cli): improve the experience by providing help by default and allowing InteractionBot to be used

tests/ext/commands/test_view.py
simple basic tests for command views.
=> tests: add basic command view tests

docs/whats_new.rst
forward port the 2.6.1 changelog
=> docs: forward port v2.6.1 changelog

.github/workflows/lint-test.yml, changelog/785.feature.rst, changelog/827.feature.rst, changelog/829.feature.rst, changelog/833.feature.rst, setup.py
adds official support for python 3.11
=> feat: officially support python 3.11

.github/workflows/lint-test.yml
=> backport(6c69226a): fix(ci): indent quoted multiline string

changelog/818.bugfix.rst, changelog/820.bugfix.rst, changelog/825.bugfix.rst, disnake/__init__.py, docs/whats_new.rst
=> release: 2.6.2

disnake/__init__.py
=> bump to 2.8.0a

.github/workflows/lint-test.yml
already partially changed in #829.
=> fix(ci): remove 3.11 alpha versions

.github/actions/setup-env/action.yml, .github/workflows/lint-test.yml
windows doing windows things :/
see https://github.com/DisnakeDev/disnake/actions/runs/3405148824/jobs/5662908901#step:3:67
=> fix(ci): use `python -m pip`

disnake/enums.py
=> chore: use bitshifting for all bitwise enums

changelog/888.doc.rst, examples/views/select/dropdown.py
Minor change just to be consistent and avoid this:
=> docs: add missing description to example

changelog/864.doc.rst, disnake/invite.py
Fixes backticks, adds missing `Optional[]` types, and adds links back to the table explaining the conditions under which attributes exist.
=> docs: update/cleanup `Invite` documentation

changelog/910.feature.rst, disnake/enums.py, docs/api.rst
https://github.com/discord/discord-api-docs/pull/5833, the endpoint currently gives an error so I'm unable to test it atm
=> feat(Sticker): support gif stickers

changelog/931.doc.rst, disnake/automod.py
https://github.com/discord/discord-api-docs/commit/81a1acc98bce6b472287ffd5f39e181abb3d3a5b
=> docs: update automod rule limits

.pre-commit-config.yaml, disnake/ext/commands/bot.py, disnake/ext/commands/interaction_bot_base.py, disnake/guild.py, disnake/interactions/base.py, disnake/iterators.py, disnake/player.py, disnake/types/gateway.py, disnake/types/interactions.py, disnake/ui/view.py, disnake/welcome_screen.py, docs/extensions/attributetable.py, examples/interactions/param.py, requirements/requirements_tools.txt, scripts/codemods/typed_flags.py, tests/ext/commands/test_view.py
update black to the newest version for the newest formatting changes.
Quite a welcome diff IMO!
=> deps: update black to 23.1.0

changelog/936.misc.rst, changelog/_template.rst.jinja, docs/_templates/layout.html, requirements/requirements_docs.txt, requirements/requirements_tools.txt
update sphinx to 6.0.1. This is semi-untested, making a pr for the rtd preview.
=> deps: update sphinx to 6.0.1

.github/workflows/lint-test.yml
new pr of #933 as it was zombiefied
=>  ci: allow usage of merge queues #933 

.github/PULL_REQUEST_TEMPLATE.md, pyproject.toml
=> fix: update excess taskipy references/installation

changelog/962.feature.rst, disnake/voice_region.py
Adds `VoiceRegion.__eq__`, based on the region's `id` (unique).
=> feat: add `VoiceRegion.__eq__`

docs/whats_new.rst
https://github.com/DisnakeDev/disnake/tree/v2.7.x
https://github.com/DisnakeDev/disnake/tree/v2.8.x
=> docs: forward-port 2.7.2/2.8.1 changelogs

changelog/976.feature.rst, disnake/ext/commands/common_bot_base.py
=> feat(bot): add a new `get_listeners` method

.pre-commit-config.yaml, disnake/client.py, disnake/ext/commands/bot_base.py, disnake/ext/commands/common_bot_base.py, disnake/ext/commands/interaction_bot_base.py, disnake/guild.py, disnake/http.py, disnake/opus.py, disnake/voice_client.py, noxfile.py, pyproject.toml
https://github.com/charliermarsh/ruff/compare/v0.0.252...v0.0.256
Some bugs pertaining to import autofix and `--ignore-noqa` were squashed.
Full changelogs: 
- https://github.com/charliermarsh/ruff/releases/tag/v0.0.256
- https://github.com/charliermarsh/ruff/releases/tag/v0.0.255
- https://github.com/charliermarsh/ruff/releases/tag/v0.0.254
- https://github.com/charliermarsh/ruff/releases/tag/v0.0.253
=> deps: update ruff to 0.0.257

disnake/permissions.py
adds type checking support to the internals of disnake.Permissions.all_channel
=> refactor(permissions): use the typed update method for all_channel()

docs/api/events.rst
=> docs: sort event categories alphabetically

.github/actions/setup-env/action.yml
=> fix(ci): pin `urllib3<2` for pdm

.gitignore, README.md
=> docs: add ci status badge

changelog/1041.feature.rst, disnake/flags.py, disnake/message.py, disnake/types/message.py
https://github.com/discord/discord-api-docs/commit/70bc0f05a90b952f376ac2071dba52225dedf7c6
see also #1006
=> feat: voice messages

pyproject.toml
=> build(deps): bump sphinx to 7.0.1

pyproject.toml
https://towncrier.readthedocs.io/en/stable/release-notes.html#towncrier-23-6-0-2023-06-06
=> build(deps): bump towncrier to 23.6.0

.github/workflows/lint-test.yml
Removes the test coverage CI steps, since they mostly slow down the pipeline and aren't being actively used.
=> ci: remove coveralls

.gitignore, disnake/client.py, disnake/guild.py
=> docs: clarify `Guild.fetch_member` raised exceptions

test_bot/__main__.py
this has been bugging me for a while
Functionality is effectively unchanged, except for fixing the `logger.error` call actually log the error.
At some point in the future, this entire thing should probably be moved to a separate repo.
=> chore(testbot): refactor error handling into one common handler

CONTRIBUTING.md, changelog/1098.misc.rst
A general overhaul of the entire contribution guide, hopefully making it easier to follow and understand. Also includes the documentation side of #196, i.e. outlining the commit/PR naming convention.
This removes the detailed example which, while insightful, was way too lengthy for new contributors. We could maybe re-add it on a separate page in the future, but for now it's too much for this guide.
preview: https://github.com/DisnakeDev/disnake/blob/docs/contributing-once-more/CONTRIBUTING.md
=> docs: rewrite CONTRIBUTING.md

changelog/1102.bugfix.rst, changelog/1102.feature.rst, disnake/colour.py
Resolves #1100. Adds `light_embed` and `dark_embed`, and updates `dark_theme` to match the latest dark theme.
=> feat(colour): update and add new theme color values

.github/workflows/create-release-pr.yaml, .github/workflows/semantic-pr-title.yml
now using `chore(release):`, instead of just `release:`.
=> fix(ci): adjust automatic release PR title to match commit format

disnake/member.py
https://discord.com/developers/docs/change-log#modify-guild-member-flags-field-permissions
=> docs: update required permissions for editing member flags

changelog/1221.feature.rst, disnake/client.py, disnake/http.py
=> feat(client): implement new sticker pack endpoint

changelog/1218.feature.rst, disnake/message.py, disnake/types/message.py
=> feat(message): add Attachment.title

changelog/1175.feature.rst
I forgot to update the names in the changelog so they weren't linking to the correct sections in the docs. Idk how but the docs check didn't pick it up.
=> fix(changelog): fix poll changelog

changelog/1304.misc.rst, examples/basic_voice.py
Doing this can cause a weird bug while using yt_dlp. According to maintener of yt_dlp, it's not recommended to do this.
=> docs: remove bad code snippet that can cause bugs

changelog/1319.feature.rst, disnake/interactions/application_command.py, disnake/interactions/base.py, disnake/interactions/message.py, disnake/interactions/modal.py, disnake/types/interactions.py
https://github.com/discord/discord-api-docs/commit/2c09c19557750d42bcc6dc699139178b7a49b363
=> feat(interactions): add `attachment_size_limit`

.pre-commit-config.yaml, changelog/1326.misc.rst, disnake/abc.py, disnake/components.py, disnake/ext/commands/base_core.py, disnake/ext/commands/cog.py, disnake/ext/commands/core.py, disnake/ext/commands/flag_converter.py, disnake/interactions/base.py, docs/extensions/fulltoc.py, pyproject.toml, tests/ext/commands/test_params.py, tests/test_abc.py, tests/test_utils.py
=> chore: bump ruff

changelog/1269.feature.rst, changelog/1276.deprecate.rst, changelog/1296.deprecate.rst, changelog/1304.misc.rst, changelog/1313.feature.rst, changelog/1333.feature.rst
=> chore(docs): miscellaneous changelog fixes

.github/workflows/lint-test.yml, disnake/bans.py
https://docs.astral.sh/ruff/settings/#output-format
=> ci: enable ruff output formatting for pre-commit
